//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GnPlatForm.MySql
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class guangzhou_0410Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new guangzhou_0410Entities object using the connection string found in the 'guangzhou_0410Entities' section of the application configuration file.
        /// </summary>
        public guangzhou_0410Entities() : base("name=guangzhou_0410Entities", "guangzhou_0410Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new guangzhou_0410Entities object.
        /// </summary>
        public guangzhou_0410Entities(string connectionString) : base(connectionString, "guangzhou_0410Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new guangzhou_0410Entities object.
        /// </summary>
        public guangzhou_0410Entities(EntityConnection connection) : base(connection, "guangzhou_0410Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gn_common_201204181300> gn_common_201204181300
        {
            get
            {
                if ((_gn_common_201204181300 == null))
                {
                    _gn_common_201204181300 = base.CreateObjectSet<gn_common_201204181300>("gn_common_201204181300");
                }
                return _gn_common_201204181300;
            }
        }
        private ObjectSet<gn_common_201204181300> _gn_common_201204181300;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gn_common_201204181300 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogn_common_201204181300(gn_common_201204181300 gn_common_201204181300)
        {
            base.AddObject("gn_common_201204181300", gn_common_201204181300);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="guangzhou_0410Model", Name="gn_common_201204181300")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gn_common_201204181300 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gn_common_201204181300 object.
        /// </summary>
        /// <param name="abnormal_reason">Initial value of the Abnormal_reason property.</param>
        /// <param name="abort">Initial value of the abort property.</param>
        /// <param name="aPN">Initial value of the APN property.</param>
        /// <param name="cI">Initial value of the CI property.</param>
        /// <param name="content_Type">Initial value of the Content_Type property.</param>
        /// <param name="delete_PDP">Initial value of the Delete_PDP property.</param>
        /// <param name="delete_PDP_Direction">Initial value of the Delete_PDP_Direction property.</param>
        /// <param name="dEST_IP">Initial value of the DEST_IP property.</param>
        /// <param name="disconnect">Initial value of the Disconnect property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="end_Date_Time">Initial value of the End_Date_Time property.</param>
        /// <param name="event_Type">Initial value of the Event_Type property.</param>
        /// <param name="gGSN">Initial value of the GGSN property.</param>
        /// <param name="gGSN_IP">Initial value of the GGSN_IP property.</param>
        /// <param name="iMEI">Initial value of the IMEI property.</param>
        /// <param name="iMSI">Initial value of the IMSI property.</param>
        /// <param name="iP_LEN_DL">Initial value of the IP_LEN_DL property.</param>
        /// <param name="iP_LEN_UL">Initial value of the IP_LEN_UL property.</param>
        /// <param name="isReassemble">Initial value of the IsReassemble property.</param>
        /// <param name="is_UserAbnormal">Initial value of the Is_UserAbnormal property.</param>
        /// <param name="lAC">Initial value of the LAC property.</param>
        /// <param name="mMS_request">Initial value of the MMS_request property.</param>
        /// <param name="mSISDN">Initial value of the MSISDN property.</param>
        /// <param name="online_ID">Initial value of the Online_ID property.</param>
        /// <param name="prefix_IMEI">Initial value of the Prefix_IMEI property.</param>
        /// <param name="pROTOCOL">Initial value of the PROTOCOL property.</param>
        /// <param name="rAT_TYPE">Initial value of the RAT_TYPE property.</param>
        /// <param name="repeat_Count">Initial value of the Repeat_Count property.</param>
        /// <param name="result">Initial value of the Result property.</param>
        /// <param name="sAC">Initial value of the SAC property.</param>
        /// <param name="service_TYPE">Initial value of the Service_TYPE property.</param>
        /// <param name="session_ID">Initial value of the Session_ID property.</param>
        /// <param name="sGSN">Initial value of the SGSN property.</param>
        /// <param name="sGSN_IP">Initial value of the SGSN_IP property.</param>
        /// <param name="sOURCE_IP">Initial value of the SOURCE_IP property.</param>
        /// <param name="start_Date_Time">Initial value of the Start_Date_Time property.</param>
        /// <param name="sub_Service_Type">Initial value of the Sub_Service_Type property.</param>
        /// <param name="uRI">Initial value of the URI property.</param>
        /// <param name="uRI_Main">Initial value of the URI_Main property.</param>
        /// <param name="user_Agent_Main">Initial value of the User_Agent_Main property.</param>
        public static gn_common_201204181300 Creategn_common_201204181300(global::System.Int32 abnormal_reason, global::System.Boolean abort, global::System.String aPN, global::System.Int64 cI, global::System.String content_Type, global::System.Boolean delete_PDP, global::System.Boolean delete_PDP_Direction, global::System.Int64 dEST_IP, global::System.Boolean disconnect, global::System.Decimal duration, global::System.DateTimeOffset end_Date_Time, global::System.SByte event_Type, global::System.String gGSN, global::System.Int64 gGSN_IP, global::System.String iMEI, global::System.String iMSI, global::System.Int64 iP_LEN_DL, global::System.Int64 iP_LEN_UL, global::System.Boolean isReassemble, global::System.Int64 is_UserAbnormal, global::System.Int64 lAC, global::System.Boolean mMS_request, global::System.Decimal mSISDN, global::System.Decimal online_ID, global::System.String prefix_IMEI, global::System.SByte pROTOCOL, global::System.Byte rAT_TYPE, global::System.Int32 repeat_Count, global::System.Boolean result, global::System.Int64 sAC, global::System.Int32 service_TYPE, global::System.Decimal session_ID, global::System.String sGSN, global::System.Int64 sGSN_IP, global::System.Int64 sOURCE_IP, global::System.DateTimeOffset start_Date_Time, global::System.Int32 sub_Service_Type, global::System.String uRI, global::System.String uRI_Main, global::System.String user_Agent_Main)
        {
            gn_common_201204181300 gn_common_201204181300 = new gn_common_201204181300();
            gn_common_201204181300.Abnormal_reason = abnormal_reason;
            gn_common_201204181300.abort = abort;
            gn_common_201204181300.APN = aPN;
            gn_common_201204181300.CI = cI;
            gn_common_201204181300.Content_Type = content_Type;
            gn_common_201204181300.Delete_PDP = delete_PDP;
            gn_common_201204181300.Delete_PDP_Direction = delete_PDP_Direction;
            gn_common_201204181300.DEST_IP = dEST_IP;
            gn_common_201204181300.Disconnect = disconnect;
            gn_common_201204181300.Duration = duration;
            gn_common_201204181300.End_Date_Time = end_Date_Time;
            gn_common_201204181300.Event_Type = event_Type;
            gn_common_201204181300.GGSN = gGSN;
            gn_common_201204181300.GGSN_IP = gGSN_IP;
            gn_common_201204181300.IMEI = iMEI;
            gn_common_201204181300.IMSI = iMSI;
            gn_common_201204181300.IP_LEN_DL = iP_LEN_DL;
            gn_common_201204181300.IP_LEN_UL = iP_LEN_UL;
            gn_common_201204181300.IsReassemble = isReassemble;
            gn_common_201204181300.Is_UserAbnormal = is_UserAbnormal;
            gn_common_201204181300.LAC = lAC;
            gn_common_201204181300.MMS_request = mMS_request;
            gn_common_201204181300.MSISDN = mSISDN;
            gn_common_201204181300.Online_ID = online_ID;
            gn_common_201204181300.Prefix_IMEI = prefix_IMEI;
            gn_common_201204181300.PROTOCOL = pROTOCOL;
            gn_common_201204181300.RAT_TYPE = rAT_TYPE;
            gn_common_201204181300.Repeat_Count = repeat_Count;
            gn_common_201204181300.Result = result;
            gn_common_201204181300.SAC = sAC;
            gn_common_201204181300.Service_TYPE = service_TYPE;
            gn_common_201204181300.Session_ID = session_ID;
            gn_common_201204181300.SGSN = sGSN;
            gn_common_201204181300.SGSN_IP = sGSN_IP;
            gn_common_201204181300.SOURCE_IP = sOURCE_IP;
            gn_common_201204181300.Start_Date_Time = start_Date_Time;
            gn_common_201204181300.Sub_Service_Type = sub_Service_Type;
            gn_common_201204181300.URI = uRI;
            gn_common_201204181300.URI_Main = uRI_Main;
            gn_common_201204181300.User_Agent_Main = user_Agent_Main;
            return gn_common_201204181300;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Abnormal_reason
        {
            get
            {
                return _Abnormal_reason;
            }
            set
            {
                OnAbnormal_reasonChanging(value);
                ReportPropertyChanging("Abnormal_reason");
                _Abnormal_reason = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Abnormal_reason");
                OnAbnormal_reasonChanged();
            }
        }
        private global::System.Int32 _Abnormal_reason;
        partial void OnAbnormal_reasonChanging(global::System.Int32 value);
        partial void OnAbnormal_reasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean abort
        {
            get
            {
                return _abort;
            }
            set
            {
                OnabortChanging(value);
                ReportPropertyChanging("abort");
                _abort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("abort");
                OnabortChanged();
            }
        }
        private global::System.Boolean _abort;
        partial void OnabortChanging(global::System.Boolean value);
        partial void OnabortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Ack
        {
            get
            {
                return _Ack;
            }
            set
            {
                OnAckChanging(value);
                ReportPropertyChanging("Ack");
                _Ack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ack");
                OnAckChanged();
            }
        }
        private Nullable<global::System.Int64> _Ack;
        partial void OnAckChanging(Nullable<global::System.Int64> value);
        partial void OnAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String APN
        {
            get
            {
                return _APN;
            }
            set
            {
                OnAPNChanging(value);
                ReportPropertyChanging("APN");
                _APN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("APN");
                OnAPNChanged();
            }
        }
        private global::System.String _APN;
        partial void OnAPNChanging(global::System.String value);
        partial void OnAPNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CI
        {
            get
            {
                return _CI;
            }
            set
            {
                OnCIChanging(value);
                ReportPropertyChanging("CI");
                _CI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CI");
                OnCIChanged();
            }
        }
        private global::System.Int64 _CI;
        partial void OnCIChanging(global::System.Int64 value);
        partial void OnCIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content_Type
        {
            get
            {
                return _Content_Type;
            }
            set
            {
                OnContent_TypeChanging(value);
                ReportPropertyChanging("Content_Type");
                _Content_Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content_Type");
                OnContent_TypeChanged();
            }
        }
        private global::System.String _Content_Type;
        partial void OnContent_TypeChanging(global::System.String value);
        partial void OnContent_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Count_Packet_DL
        {
            get
            {
                return _Count_Packet_DL;
            }
            set
            {
                OnCount_Packet_DLChanging(value);
                ReportPropertyChanging("Count_Packet_DL");
                _Count_Packet_DL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count_Packet_DL");
                OnCount_Packet_DLChanged();
            }
        }
        private Nullable<global::System.Int64> _Count_Packet_DL;
        partial void OnCount_Packet_DLChanging(Nullable<global::System.Int64> value);
        partial void OnCount_Packet_DLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Count_Packet_UL
        {
            get
            {
                return _Count_Packet_UL;
            }
            set
            {
                OnCount_Packet_ULChanging(value);
                ReportPropertyChanging("Count_Packet_UL");
                _Count_Packet_UL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count_Packet_UL");
                OnCount_Packet_ULChanged();
            }
        }
        private Nullable<global::System.Int64> _Count_Packet_UL;
        partial void OnCount_Packet_ULChanging(Nullable<global::System.Int64> value);
        partial void OnCount_Packet_ULChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Delete_PDP
        {
            get
            {
                return _Delete_PDP;
            }
            set
            {
                OnDelete_PDPChanging(value);
                ReportPropertyChanging("Delete_PDP");
                _Delete_PDP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delete_PDP");
                OnDelete_PDPChanged();
            }
        }
        private global::System.Boolean _Delete_PDP;
        partial void OnDelete_PDPChanging(global::System.Boolean value);
        partial void OnDelete_PDPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Delete_PDP_Direction
        {
            get
            {
                return _Delete_PDP_Direction;
            }
            set
            {
                OnDelete_PDP_DirectionChanging(value);
                ReportPropertyChanging("Delete_PDP_Direction");
                _Delete_PDP_Direction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delete_PDP_Direction");
                OnDelete_PDP_DirectionChanged();
            }
        }
        private global::System.Boolean _Delete_PDP_Direction;
        partial void OnDelete_PDP_DirectionChanging(global::System.Boolean value);
        partial void OnDelete_PDP_DirectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Delivery_Report
        {
            get
            {
                return _Delivery_Report;
            }
            set
            {
                OnDelivery_ReportChanging(value);
                ReportPropertyChanging("Delivery_Report");
                _Delivery_Report = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delivery_Report");
                OnDelivery_ReportChanged();
            }
        }
        private Nullable<global::System.Boolean> _Delivery_Report;
        partial void OnDelivery_ReportChanging(Nullable<global::System.Boolean> value);
        partial void OnDelivery_ReportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DEST_IP
        {
            get
            {
                return _DEST_IP;
            }
            set
            {
                OnDEST_IPChanging(value);
                ReportPropertyChanging("DEST_IP");
                _DEST_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEST_IP");
                OnDEST_IPChanged();
            }
        }
        private global::System.Int64 _DEST_IP;
        partial void OnDEST_IPChanging(global::System.Int64 value);
        partial void OnDEST_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DEST_PORT
        {
            get
            {
                return _DEST_PORT;
            }
            set
            {
                OnDEST_PORTChanging(value);
                ReportPropertyChanging("DEST_PORT");
                _DEST_PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEST_PORT");
                OnDEST_PORTChanged();
            }
        }
        private Nullable<global::System.Int32> _DEST_PORT;
        partial void OnDEST_PORTChanging(Nullable<global::System.Int32> value);
        partial void OnDEST_PORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Disconnect
        {
            get
            {
                return _Disconnect;
            }
            set
            {
                OnDisconnectChanging(value);
                ReportPropertyChanging("Disconnect");
                _Disconnect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Disconnect");
                OnDisconnectChanged();
            }
        }
        private global::System.Boolean _Disconnect;
        partial void OnDisconnectChanging(global::System.Boolean value);
        partial void OnDisconnectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DNS_TTL
        {
            get
            {
                return _DNS_TTL;
            }
            set
            {
                OnDNS_TTLChanging(value);
                ReportPropertyChanging("DNS_TTL");
                _DNS_TTL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNS_TTL");
                OnDNS_TTLChanged();
            }
        }
        private Nullable<global::System.Int64> _DNS_TTL;
        partial void OnDNS_TTLChanging(Nullable<global::System.Int64> value);
        partial void OnDNS_TTLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Decimal _Duration;
        partial void OnDurationChanging(global::System.Decimal value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset End_Date_Time
        {
            get
            {
                return _End_Date_Time;
            }
            set
            {
                OnEnd_Date_TimeChanging(value);
                ReportPropertyChanging("End_Date_Time");
                _End_Date_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End_Date_Time");
                OnEnd_Date_TimeChanged();
            }
        }
        private global::System.DateTimeOffset _End_Date_Time;
        partial void OnEnd_Date_TimeChanging(global::System.DateTimeOffset value);
        partial void OnEnd_Date_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ErrorPacketLost
        {
            get
            {
                return _ErrorPacketLost;
            }
            set
            {
                OnErrorPacketLostChanging(value);
                ReportPropertyChanging("ErrorPacketLost");
                _ErrorPacketLost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketLost");
                OnErrorPacketLostChanged();
            }
        }
        private Nullable<global::System.Int64> _ErrorPacketLost;
        partial void OnErrorPacketLostChanging(Nullable<global::System.Int64> value);
        partial void OnErrorPacketLostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ErrorPacketWired
        {
            get
            {
                return _ErrorPacketWired;
            }
            set
            {
                OnErrorPacketWiredChanging(value);
                ReportPropertyChanging("ErrorPacketWired");
                _ErrorPacketWired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketWired");
                OnErrorPacketWiredChanged();
            }
        }
        private Nullable<global::System.Int64> _ErrorPacketWired;
        partial void OnErrorPacketWiredChanging(Nullable<global::System.Int64> value);
        partial void OnErrorPacketWiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ErrorPacketWireless
        {
            get
            {
                return _ErrorPacketWireless;
            }
            set
            {
                OnErrorPacketWirelessChanging(value);
                ReportPropertyChanging("ErrorPacketWireless");
                _ErrorPacketWireless = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketWireless");
                OnErrorPacketWirelessChanged();
            }
        }
        private Nullable<global::System.Int64> _ErrorPacketWireless;
        partial void OnErrorPacketWirelessChanging(Nullable<global::System.Int64> value);
        partial void OnErrorPacketWirelessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte Event_Type
        {
            get
            {
                return _Event_Type;
            }
            set
            {
                OnEvent_TypeChanging(value);
                ReportPropertyChanging("Event_Type");
                _Event_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Event_Type");
                OnEvent_TypeChanged();
            }
        }
        private global::System.SByte _Event_Type;
        partial void OnEvent_TypeChanging(global::System.SByte value);
        partial void OnEvent_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GGSN
        {
            get
            {
                return _GGSN;
            }
            set
            {
                OnGGSNChanging(value);
                ReportPropertyChanging("GGSN");
                _GGSN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GGSN");
                OnGGSNChanged();
            }
        }
        private global::System.String _GGSN;
        partial void OnGGSNChanging(global::System.String value);
        partial void OnGGSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 GGSN_IP
        {
            get
            {
                return _GGSN_IP;
            }
            set
            {
                OnGGSN_IPChanging(value);
                ReportPropertyChanging("GGSN_IP");
                _GGSN_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GGSN_IP");
                OnGGSN_IPChanged();
            }
        }
        private global::System.Int64 _GGSN_IP;
        partial void OnGGSN_IPChanging(global::System.Int64 value);
        partial void OnGGSN_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ICMP_Code
        {
            get
            {
                return _ICMP_Code;
            }
            set
            {
                OnICMP_CodeChanging(value);
                ReportPropertyChanging("ICMP_Code");
                _ICMP_Code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ICMP_Code");
                OnICMP_CodeChanged();
            }
        }
        private Nullable<global::System.Int64> _ICMP_Code;
        partial void OnICMP_CodeChanging(Nullable<global::System.Int64> value);
        partial void OnICMP_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ICMP_Type
        {
            get
            {
                return _ICMP_Type;
            }
            set
            {
                OnICMP_TypeChanging(value);
                ReportPropertyChanging("ICMP_Type");
                _ICMP_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ICMP_Type");
                OnICMP_TypeChanged();
            }
        }
        private Nullable<global::System.Int64> _ICMP_Type;
        partial void OnICMP_TypeChanging(Nullable<global::System.Int64> value);
        partial void OnICMP_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Identifier
        {
            get
            {
                return _Identifier;
            }
            set
            {
                OnIdentifierChanging(value);
                ReportPropertyChanging("Identifier");
                _Identifier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Identifier");
                OnIdentifierChanged();
            }
        }
        private Nullable<global::System.Int64> _Identifier;
        partial void OnIdentifierChanging(Nullable<global::System.Int64> value);
        partial void OnIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private global::System.String _IMEI;
        partial void OnIMEIChanging(global::System.String value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMSI
        {
            get
            {
                return _IMSI;
            }
            set
            {
                OnIMSIChanging(value);
                ReportPropertyChanging("IMSI");
                _IMSI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMSI");
                OnIMSIChanged();
            }
        }
        private global::System.String _IMSI;
        partial void OnIMSIChanging(global::System.String value);
        partial void OnIMSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IP3_Dest
        {
            get
            {
                return _IP3_Dest;
            }
            set
            {
                OnIP3_DestChanging(value);
                ReportPropertyChanging("IP3_Dest");
                _IP3_Dest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP3_Dest");
                OnIP3_DestChanged();
            }
        }
        private Nullable<global::System.Int64> _IP3_Dest;
        partial void OnIP3_DestChanging(Nullable<global::System.Int64> value);
        partial void OnIP3_DestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IP3_Len
        {
            get
            {
                return _IP3_Len;
            }
            set
            {
                OnIP3_LenChanging(value);
                ReportPropertyChanging("IP3_Len");
                _IP3_Len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP3_Len");
                OnIP3_LenChanged();
            }
        }
        private Nullable<global::System.Int64> _IP3_Len;
        partial void OnIP3_LenChanging(Nullable<global::System.Int64> value);
        partial void OnIP3_LenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IP3_Src
        {
            get
            {
                return _IP3_Src;
            }
            set
            {
                OnIP3_SrcChanging(value);
                ReportPropertyChanging("IP3_Src");
                _IP3_Src = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP3_Src");
                OnIP3_SrcChanged();
            }
        }
        private Nullable<global::System.Int64> _IP3_Src;
        partial void OnIP3_SrcChanging(Nullable<global::System.Int64> value);
        partial void OnIP3_SrcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IpLenDlAck
        {
            get
            {
                return _IpLenDlAck;
            }
            set
            {
                OnIpLenDlAckChanging(value);
                ReportPropertyChanging("IpLenDlAck");
                _IpLenDlAck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IpLenDlAck");
                OnIpLenDlAckChanged();
            }
        }
        private Nullable<global::System.Int64> _IpLenDlAck;
        partial void OnIpLenDlAckChanging(Nullable<global::System.Int64> value);
        partial void OnIpLenDlAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IpLenUpAck
        {
            get
            {
                return _IpLenUpAck;
            }
            set
            {
                OnIpLenUpAckChanging(value);
                ReportPropertyChanging("IpLenUpAck");
                _IpLenUpAck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IpLenUpAck");
                OnIpLenUpAckChanged();
            }
        }
        private Nullable<global::System.Int64> _IpLenUpAck;
        partial void OnIpLenUpAckChanging(Nullable<global::System.Int64> value);
        partial void OnIpLenUpAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IP_LEN_DL
        {
            get
            {
                return _IP_LEN_DL;
            }
            set
            {
                OnIP_LEN_DLChanging(value);
                ReportPropertyChanging("IP_LEN_DL");
                _IP_LEN_DL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP_LEN_DL");
                OnIP_LEN_DLChanged();
            }
        }
        private global::System.Int64 _IP_LEN_DL;
        partial void OnIP_LEN_DLChanging(global::System.Int64 value);
        partial void OnIP_LEN_DLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IP_LEN_UL
        {
            get
            {
                return _IP_LEN_UL;
            }
            set
            {
                OnIP_LEN_ULChanging(value);
                ReportPropertyChanging("IP_LEN_UL");
                _IP_LEN_UL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP_LEN_UL");
                OnIP_LEN_ULChanged();
            }
        }
        private global::System.Int64 _IP_LEN_UL;
        partial void OnIP_LEN_ULChanging(global::System.Int64 value);
        partial void OnIP_LEN_ULChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReassemble
        {
            get
            {
                return _IsReassemble;
            }
            set
            {
                OnIsReassembleChanging(value);
                ReportPropertyChanging("IsReassemble");
                _IsReassemble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReassemble");
                OnIsReassembleChanged();
            }
        }
        private global::System.Boolean _IsReassemble;
        partial void OnIsReassembleChanging(global::System.Boolean value);
        partial void OnIsReassembleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Is_UserAbnormal
        {
            get
            {
                return _Is_UserAbnormal;
            }
            set
            {
                OnIs_UserAbnormalChanging(value);
                ReportPropertyChanging("Is_UserAbnormal");
                _Is_UserAbnormal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Is_UserAbnormal");
                OnIs_UserAbnormalChanged();
            }
        }
        private global::System.Int64 _Is_UserAbnormal;
        partial void OnIs_UserAbnormalChanging(global::System.Int64 value);
        partial void OnIs_UserAbnormalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LAC
        {
            get
            {
                return _LAC;
            }
            set
            {
                OnLACChanging(value);
                ReportPropertyChanging("LAC");
                _LAC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAC");
                OnLACChanged();
            }
        }
        private global::System.Int64 _LAC;
        partial void OnLACChanging(global::System.Int64 value);
        partial void OnLACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MMS_request
        {
            get
            {
                return _MMS_request;
            }
            set
            {
                OnMMS_requestChanging(value);
                ReportPropertyChanging("MMS_request");
                _MMS_request = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MMS_request");
                OnMMS_requestChanged();
            }
        }
        private global::System.Boolean _MMS_request;
        partial void OnMMS_requestChanging(global::System.Boolean value);
        partial void OnMMS_requestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> MMS_resp_status
        {
            get
            {
                return _MMS_resp_status;
            }
            set
            {
                OnMMS_resp_statusChanging(value);
                ReportPropertyChanging("MMS_resp_status");
                _MMS_resp_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MMS_resp_status");
                OnMMS_resp_statusChanged();
            }
        }
        private Nullable<global::System.Byte> _MMS_resp_status;
        partial void OnMMS_resp_statusChanging(Nullable<global::System.Byte> value);
        partial void OnMMS_resp_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MSISDN
        {
            get
            {
                return _MSISDN;
            }
            set
            {
                OnMSISDNChanging(value);
                ReportPropertyChanging("MSISDN");
                _MSISDN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MSISDN");
                OnMSISDNChanged();
            }
        }
        private global::System.Decimal _MSISDN;
        partial void OnMSISDNChanging(global::System.Decimal value);
        partial void OnMSISDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Online_ID
        {
            get
            {
                return _Online_ID;
            }
            set
            {
                OnOnline_IDChanging(value);
                ReportPropertyChanging("Online_ID");
                _Online_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Online_ID");
                OnOnline_IDChanged();
            }
        }
        private global::System.Decimal _Online_ID;
        partial void OnOnline_IDChanging(global::System.Decimal value);
        partial void OnOnline_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prefix_IMEI
        {
            get
            {
                return _Prefix_IMEI;
            }
            set
            {
                OnPrefix_IMEIChanging(value);
                ReportPropertyChanging("Prefix_IMEI");
                _Prefix_IMEI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prefix_IMEI");
                OnPrefix_IMEIChanged();
            }
        }
        private global::System.String _Prefix_IMEI;
        partial void OnPrefix_IMEIChanging(global::System.String value);
        partial void OnPrefix_IMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte PROTOCOL
        {
            get
            {
                return _PROTOCOL;
            }
            set
            {
                OnPROTOCOLChanging(value);
                ReportPropertyChanging("PROTOCOL");
                _PROTOCOL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROTOCOL");
                OnPROTOCOLChanged();
            }
        }
        private global::System.SByte _PROTOCOL;
        partial void OnPROTOCOLChanging(global::System.SByte value);
        partial void OnPROTOCOLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Query_Name
        {
            get
            {
                return _Query_Name;
            }
            set
            {
                OnQuery_NameChanging(value);
                ReportPropertyChanging("Query_Name");
                _Query_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Query_Name");
                OnQuery_NameChanged();
            }
        }
        private global::System.String _Query_Name;
        partial void OnQuery_NameChanging(global::System.String value);
        partial void OnQuery_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Query_Type
        {
            get
            {
                return _Query_Type;
            }
            set
            {
                OnQuery_TypeChanging(value);
                ReportPropertyChanging("Query_Type");
                _Query_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Query_Type");
                OnQuery_TypeChanged();
            }
        }
        private global::System.String _Query_Type;
        partial void OnQuery_TypeChanging(global::System.String value);
        partial void OnQuery_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte RAT_TYPE
        {
            get
            {
                return _RAT_TYPE;
            }
            set
            {
                OnRAT_TYPEChanging(value);
                ReportPropertyChanging("RAT_TYPE");
                _RAT_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RAT_TYPE");
                OnRAT_TYPEChanged();
            }
        }
        private global::System.Byte _RAT_TYPE;
        partial void OnRAT_TYPEChanging(global::System.Byte value);
        partial void OnRAT_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Repeat_Count
        {
            get
            {
                return _Repeat_Count;
            }
            set
            {
                OnRepeat_CountChanging(value);
                ReportPropertyChanging("Repeat_Count");
                _Repeat_Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Repeat_Count");
                OnRepeat_CountChanged();
            }
        }
        private global::System.Int32 _Repeat_Count;
        partial void OnRepeat_CountChanging(global::System.Int32 value);
        partial void OnRepeat_CountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Resp
        {
            get
            {
                return _Resp;
            }
            set
            {
                OnRespChanging(value);
                ReportPropertyChanging("Resp");
                _Resp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp");
                OnRespChanged();
            }
        }
        private Nullable<global::System.Boolean> _Resp;
        partial void OnRespChanging(Nullable<global::System.Boolean> value);
        partial void OnRespChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Resp_cause
        {
            get
            {
                return _Resp_cause;
            }
            set
            {
                OnResp_causeChanging(value);
                ReportPropertyChanging("Resp_cause");
                _Resp_cause = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp_cause");
                OnResp_causeChanged();
            }
        }
        private Nullable<global::System.Int32> _Resp_cause;
        partial void OnResp_causeChanging(Nullable<global::System.Int32> value);
        partial void OnResp_causeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Resp_DelayFirst
        {
            get
            {
                return _Resp_DelayFirst;
            }
            set
            {
                OnResp_DelayFirstChanging(value);
                ReportPropertyChanging("Resp_DelayFirst");
                _Resp_DelayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp_DelayFirst");
                OnResp_DelayFirstChanged();
            }
        }
        private Nullable<global::System.Int64> _Resp_DelayFirst;
        partial void OnResp_DelayFirstChanging(Nullable<global::System.Int64> value);
        partial void OnResp_DelayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Result
        {
            get
            {
                return _Result;
            }
            set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private global::System.Boolean _Result;
        partial void OnResultChanging(global::System.Boolean value);
        partial void OnResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Result_DelayFirst
        {
            get
            {
                return _Result_DelayFirst;
            }
            set
            {
                OnResult_DelayFirstChanging(value);
                ReportPropertyChanging("Result_DelayFirst");
                _Result_DelayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result_DelayFirst");
                OnResult_DelayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _Result_DelayFirst;
        partial void OnResult_DelayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnResult_DelayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SAC
        {
            get
            {
                return _SAC;
            }
            set
            {
                OnSACChanging(value);
                ReportPropertyChanging("SAC");
                _SAC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SAC");
                OnSACChanged();
            }
        }
        private global::System.Int64 _SAC;
        partial void OnSACChanging(global::System.Int64 value);
        partial void OnSACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Service_TYPE
        {
            get
            {
                return _Service_TYPE;
            }
            set
            {
                OnService_TYPEChanging(value);
                ReportPropertyChanging("Service_TYPE");
                _Service_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Service_TYPE");
                OnService_TYPEChanged();
            }
        }
        private global::System.Int32 _Service_TYPE;
        partial void OnService_TYPEChanging(global::System.Int32 value);
        partial void OnService_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Session_ID
        {
            get
            {
                return _Session_ID;
            }
            set
            {
                if (_Session_ID != value)
                {
                    OnSession_IDChanging(value);
                    ReportPropertyChanging("Session_ID");
                    _Session_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Session_ID");
                    OnSession_IDChanged();
                }
            }
        }
        private global::System.Decimal _Session_ID;
        partial void OnSession_IDChanging(global::System.Decimal value);
        partial void OnSession_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SGSN
        {
            get
            {
                return _SGSN;
            }
            set
            {
                OnSGSNChanging(value);
                ReportPropertyChanging("SGSN");
                _SGSN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SGSN");
                OnSGSNChanged();
            }
        }
        private global::System.String _SGSN;
        partial void OnSGSNChanging(global::System.String value);
        partial void OnSGSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SGSN_IP
        {
            get
            {
                return _SGSN_IP;
            }
            set
            {
                OnSGSN_IPChanging(value);
                ReportPropertyChanging("SGSN_IP");
                _SGSN_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGSN_IP");
                OnSGSN_IPChanged();
            }
        }
        private global::System.Int64 _SGSN_IP;
        partial void OnSGSN_IPChanging(global::System.Int64 value);
        partial void OnSGSN_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SOURCE_IP
        {
            get
            {
                return _SOURCE_IP;
            }
            set
            {
                OnSOURCE_IPChanging(value);
                ReportPropertyChanging("SOURCE_IP");
                _SOURCE_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOURCE_IP");
                OnSOURCE_IPChanged();
            }
        }
        private global::System.Int64 _SOURCE_IP;
        partial void OnSOURCE_IPChanging(global::System.Int64 value);
        partial void OnSOURCE_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOURCE_PORT
        {
            get
            {
                return _SOURCE_PORT;
            }
            set
            {
                OnSOURCE_PORTChanging(value);
                ReportPropertyChanging("SOURCE_PORT");
                _SOURCE_PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOURCE_PORT");
                OnSOURCE_PORTChanged();
            }
        }
        private Nullable<global::System.Int32> _SOURCE_PORT;
        partial void OnSOURCE_PORTChanging(Nullable<global::System.Int32> value);
        partial void OnSOURCE_PORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SP_Address
        {
            get
            {
                return _SP_Address;
            }
            set
            {
                OnSP_AddressChanging(value);
                ReportPropertyChanging("SP_Address");
                _SP_Address = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SP_Address");
                OnSP_AddressChanged();
            }
        }
        private Nullable<global::System.Int64> _SP_Address;
        partial void OnSP_AddressChanging(Nullable<global::System.Int64> value);
        partial void OnSP_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Start_Date_Time
        {
            get
            {
                return _Start_Date_Time;
            }
            set
            {
                OnStart_Date_TimeChanging(value);
                ReportPropertyChanging("Start_Date_Time");
                _Start_Date_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start_Date_Time");
                OnStart_Date_TimeChanged();
            }
        }
        private global::System.DateTimeOffset _Start_Date_Time;
        partial void OnStart_Date_TimeChanging(global::System.DateTimeOffset value);
        partial void OnStart_Date_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sub_Service_Type
        {
            get
            {
                return _Sub_Service_Type;
            }
            set
            {
                OnSub_Service_TypeChanging(value);
                ReportPropertyChanging("Sub_Service_Type");
                _Sub_Service_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sub_Service_Type");
                OnSub_Service_TypeChanged();
            }
        }
        private global::System.Int32 _Sub_Service_Type;
        partial void OnSub_Service_TypeChanging(global::System.Int32 value);
        partial void OnSub_Service_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SynDirection
        {
            get
            {
                return _SynDirection;
            }
            set
            {
                OnSynDirectionChanging(value);
                ReportPropertyChanging("SynDirection");
                _SynDirection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SynDirection");
                OnSynDirectionChanged();
            }
        }
        private Nullable<global::System.Int64> _SynDirection;
        partial void OnSynDirectionChanging(Nullable<global::System.Int64> value);
        partial void OnSynDirectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UDP3_Dest
        {
            get
            {
                return _UDP3_Dest;
            }
            set
            {
                OnUDP3_DestChanging(value);
                ReportPropertyChanging("UDP3_Dest");
                _UDP3_Dest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UDP3_Dest");
                OnUDP3_DestChanged();
            }
        }
        private Nullable<global::System.Int64> _UDP3_Dest;
        partial void OnUDP3_DestChanging(Nullable<global::System.Int64> value);
        partial void OnUDP3_DestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UDP3_Len
        {
            get
            {
                return _UDP3_Len;
            }
            set
            {
                OnUDP3_LenChanging(value);
                ReportPropertyChanging("UDP3_Len");
                _UDP3_Len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UDP3_Len");
                OnUDP3_LenChanged();
            }
        }
        private Nullable<global::System.Int64> _UDP3_Len;
        partial void OnUDP3_LenChanging(Nullable<global::System.Int64> value);
        partial void OnUDP3_LenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UDP3_Src
        {
            get
            {
                return _UDP3_Src;
            }
            set
            {
                OnUDP3_SrcChanging(value);
                ReportPropertyChanging("UDP3_Src");
                _UDP3_Src = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UDP3_Src");
                OnUDP3_SrcChanged();
            }
        }
        private Nullable<global::System.Int64> _UDP3_Src;
        partial void OnUDP3_SrcChanging(Nullable<global::System.Int64> value);
        partial void OnUDP3_SrcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URI
        {
            get
            {
                return _URI;
            }
            set
            {
                OnURIChanging(value);
                ReportPropertyChanging("URI");
                _URI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URI");
                OnURIChanged();
            }
        }
        private global::System.String _URI;
        partial void OnURIChanging(global::System.String value);
        partial void OnURIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URI_Main
        {
            get
            {
                return _URI_Main;
            }
            set
            {
                OnURI_MainChanging(value);
                ReportPropertyChanging("URI_Main");
                _URI_Main = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URI_Main");
                OnURI_MainChanged();
            }
        }
        private global::System.String _URI_Main;
        partial void OnURI_MainChanging(global::System.String value);
        partial void OnURI_MainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_Agent_Main
        {
            get
            {
                return _User_Agent_Main;
            }
            set
            {
                OnUser_Agent_MainChanging(value);
                ReportPropertyChanging("User_Agent_Main");
                _User_Agent_Main = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_Agent_Main");
                OnUser_Agent_MainChanged();
            }
        }
        private global::System.String _User_Agent_Main;
        partial void OnUser_Agent_MainChanging(global::System.String value);
        partial void OnUser_Agent_MainChanged();

        #endregion
    
    }

    #endregion
    
}
