//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GnPlatForm.SqlServer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GuangZhou_GnEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GuangZhou_GnEntities2 object using the connection string found in the 'GuangZhou_GnEntities2' section of the application configuration file.
        /// </summary>
        public GuangZhou_GnEntities2() : base("name=GuangZhou_GnEntities2", "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities2 object.
        /// </summary>
        public GuangZhou_GnEntities2(string connectionString) : base(connectionString, "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities2 object.
        /// </summary>
        public GuangZhou_GnEntities2(EntityConnection connection) : base(connection, "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<imeitype> imeitype
        {
            get
            {
                if ((_imeitype == null))
                {
                    _imeitype = base.CreateObjectSet<imeitype>("imeitype");
                }
                return _imeitype;
            }
        }
        private ObjectSet<imeitype> _imeitype;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gb_XID> Gb_XID
        {
            get
            {
                if ((_Gb_XID == null))
                {
                    _Gb_XID = base.CreateObjectSet<Gb_XID>("Gb_XID");
                }
                return _Gb_XID;
            }
        }
        private ObjectSet<Gb_XID> _Gb_XID;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gb_PDP_XID> Gb_PDP_XID
        {
            get
            {
                if ((_Gb_PDP_XID == null))
                {
                    _Gb_PDP_XID = base.CreateObjectSet<Gb_PDP_XID>("Gb_PDP_XID");
                }
                return _Gb_PDP_XID;
            }
        }
        private ObjectSet<Gb_PDP_XID> _Gb_PDP_XID;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the imeitype EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToimeitype(imeitype imeitype)
        {
            base.AddObject("imeitype", imeitype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Gb_XID EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGb_XID(Gb_XID gb_XID)
        {
            base.AddObject("Gb_XID", gb_XID);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Gb_PDP_XID EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGb_PDP_XID(Gb_PDP_XID gb_PDP_XID)
        {
            base.AddObject("Gb_PDP_XID", gb_PDP_XID);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GnModel2", Name="Gb_PDP_XID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gb_PDP_XID : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gb_PDP_XID object.
        /// </summary>
        /// <param name="fileNum">Initial value of the FileNum property.</param>
        /// <param name="packetNum">Initial value of the PacketNum property.</param>
        public static Gb_PDP_XID CreateGb_PDP_XID(global::System.Int32 fileNum, global::System.Int32 packetNum)
        {
            Gb_PDP_XID gb_PDP_XID = new Gb_PDP_XID();
            gb_PDP_XID.FileNum = fileNum;
            gb_PDP_XID.PacketNum = packetNum;
            return gb_PDP_XID;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileNum
        {
            get
            {
                return _FileNum;
            }
            set
            {
                if (_FileNum != value)
                {
                    OnFileNumChanging(value);
                    ReportPropertyChanging("FileNum");
                    _FileNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileNum");
                    OnFileNumChanged();
                }
            }
        }
        private global::System.Int32 _FileNum;
        partial void OnFileNumChanging(global::System.Int32 value);
        partial void OnFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PacketNum
        {
            get
            {
                return _PacketNum;
            }
            set
            {
                if (_PacketNum != value)
                {
                    OnPacketNumChanging(value);
                    ReportPropertyChanging("PacketNum");
                    _PacketNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PacketNum");
                    OnPacketNumChanged();
                }
            }
        }
        private global::System.Int32 _PacketNum;
        partial void OnPacketNumChanging(global::System.Int32 value);
        partial void OnPacketNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFileNum
        {
            get
            {
                return _BeginFileNum;
            }
            set
            {
                OnBeginFileNumChanging(value);
                ReportPropertyChanging("BeginFileNum");
                _BeginFileNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFileNum");
                OnBeginFileNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFileNum;
        partial void OnBeginFileNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFrameNum
        {
            get
            {
                return _BeginFrameNum;
            }
            set
            {
                OnBeginFrameNumChanging(value);
                ReportPropertyChanging("BeginFrameNum");
                _BeginFrameNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFrameNum");
                OnBeginFrameNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFrameNum;
        partial void OnBeginFrameNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFrameNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PacketTime
        {
            get
            {
                return _PacketTime;
            }
            set
            {
                OnPacketTimeChanging(value);
                ReportPropertyChanging("PacketTime");
                _PacketTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime");
                OnPacketTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PacketTime;
        partial void OnPacketTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPacketTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PacketTime_ms_
        {
            get
            {
                return _PacketTime_ms_;
            }
            set
            {
                OnPacketTime_ms_Changing(value);
                ReportPropertyChanging("PacketTime_ms_");
                _PacketTime_ms_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime_ms_");
                OnPacketTime_ms_Changed();
            }
        }
        private Nullable<global::System.Int32> _PacketTime_ms_;
        partial void OnPacketTime_ms_Changing(Nullable<global::System.Int32> value);
        partial void OnPacketTime_ms_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DumpFor
        {
            get
            {
                return _DumpFor;
            }
            set
            {
                OnDumpForChanging(value);
                ReportPropertyChanging("DumpFor");
                _DumpFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DumpFor");
                OnDumpForChanged();
            }
        }
        private global::System.String _DumpFor;
        partial void OnDumpForChanging(global::System.String value);
        partial void OnDumpForChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDP_Act_Request
        {
            get
            {
                return _PDP_Act_Request;
            }
            set
            {
                OnPDP_Act_RequestChanging(value);
                ReportPropertyChanging("PDP_Act_Request");
                _PDP_Act_Request = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDP_Act_Request");
                OnPDP_Act_RequestChanged();
            }
        }
        private Nullable<global::System.Int32> _PDP_Act_Request;
        partial void OnPDP_Act_RequestChanging(Nullable<global::System.Int32> value);
        partial void OnPDP_Act_RequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PDP_Act_Request_time
        {
            get
            {
                return _PDP_Act_Request_time;
            }
            set
            {
                OnPDP_Act_Request_timeChanging(value);
                ReportPropertyChanging("PDP_Act_Request_time");
                _PDP_Act_Request_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PDP_Act_Request_time");
                OnPDP_Act_Request_timeChanged();
            }
        }
        private global::System.String _PDP_Act_Request_time;
        partial void OnPDP_Act_Request_timeChanging(global::System.String value);
        partial void OnPDP_Act_Request_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TLLI
        {
            get
            {
                return _TLLI;
            }
            set
            {
                OnTLLIChanging(value);
                ReportPropertyChanging("TLLI");
                _TLLI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TLLI");
                OnTLLIChanged();
            }
        }
        private global::System.String _TLLI;
        partial void OnTLLIChanging(global::System.String value);
        partial void OnTLLIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CI
        {
            get
            {
                return _CI;
            }
            set
            {
                OnCIChanging(value);
                ReportPropertyChanging("CI");
                _CI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CI");
                OnCIChanged();
            }
        }
        private global::System.String _CI;
        partial void OnCIChanging(global::System.String value);
        partial void OnCIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APN
        {
            get
            {
                return _APN;
            }
            set
            {
                OnAPNChanging(value);
                ReportPropertyChanging("APN");
                _APN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APN");
                OnAPNChanged();
            }
        }
        private global::System.String _APN;
        partial void OnAPNChanging(global::System.String value);
        partial void OnAPNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LAC
        {
            get
            {
                return _LAC;
            }
            set
            {
                OnLACChanging(value);
                ReportPropertyChanging("LAC");
                _LAC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LAC");
                OnLACChanged();
            }
        }
        private global::System.String _LAC;
        partial void OnLACChanging(global::System.String value);
        partial void OnLACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MCC
        {
            get
            {
                return _MCC;
            }
            set
            {
                OnMCCChanging(value);
                ReportPropertyChanging("MCC");
                _MCC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MCC");
                OnMCCChanged();
            }
        }
        private global::System.String _MCC;
        partial void OnMCCChanging(global::System.String value);
        partial void OnMCCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MNC
        {
            get
            {
                return _MNC;
            }
            set
            {
                OnMNCChanging(value);
                ReportPropertyChanging("MNC");
                _MNC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MNC");
                OnMNCChanged();
            }
        }
        private global::System.String _MNC;
        partial void OnMNCChanging(global::System.String value);
        partial void OnMNCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BVCI
        {
            get
            {
                return _BVCI;
            }
            set
            {
                OnBVCIChanging(value);
                ReportPropertyChanging("BVCI");
                _BVCI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BVCI");
                OnBVCIChanged();
            }
        }
        private global::System.String _BVCI;
        partial void OnBVCIChanging(global::System.String value);
        partial void OnBVCIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source_IP
        {
            get
            {
                return _Source_IP;
            }
            set
            {
                OnSource_IPChanging(value);
                ReportPropertyChanging("Source_IP");
                _Source_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source_IP");
                OnSource_IPChanged();
            }
        }
        private global::System.String _Source_IP;
        partial void OnSource_IPChanging(global::System.String value);
        partial void OnSource_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dest_IP
        {
            get
            {
                return _Dest_IP;
            }
            set
            {
                OnDest_IPChanging(value);
                ReportPropertyChanging("Dest_IP");
                _Dest_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dest_IP");
                OnDest_IPChanged();
            }
        }
        private global::System.String _Dest_IP;
        partial void OnDest_IPChanging(global::System.String value);
        partial void OnDest_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source_Port
        {
            get
            {
                return _Source_Port;
            }
            set
            {
                OnSource_PortChanging(value);
                ReportPropertyChanging("Source_Port");
                _Source_Port = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source_Port");
                OnSource_PortChanged();
            }
        }
        private global::System.String _Source_Port;
        partial void OnSource_PortChanging(global::System.String value);
        partial void OnSource_PortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dest_Port
        {
            get
            {
                return _Dest_Port;
            }
            set
            {
                OnDest_PortChanging(value);
                ReportPropertyChanging("Dest_Port");
                _Dest_Port = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dest_Port");
                OnDest_PortChanged();
            }
        }
        private global::System.String _Dest_Port;
        partial void OnDest_PortChanging(global::System.String value);
        partial void OnDest_PortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDP_Request_Repeat
        {
            get
            {
                return _PDP_Request_Repeat;
            }
            set
            {
                OnPDP_Request_RepeatChanging(value);
                ReportPropertyChanging("PDP_Request_Repeat");
                _PDP_Request_Repeat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDP_Request_Repeat");
                OnPDP_Request_RepeatChanged();
            }
        }
        private Nullable<global::System.Int32> _PDP_Request_Repeat;
        partial void OnPDP_Request_RepeatChanging(Nullable<global::System.Int32> value);
        partial void OnPDP_Request_RepeatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDP_Request_Repeat_delayFirst
        {
            get
            {
                return _PDP_Request_Repeat_delayFirst;
            }
            set
            {
                OnPDP_Request_Repeat_delayFirstChanging(value);
                ReportPropertyChanging("PDP_Request_Repeat_delayFirst");
                _PDP_Request_Repeat_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDP_Request_Repeat_delayFirst");
                OnPDP_Request_Repeat_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _PDP_Request_Repeat_delayFirst;
        partial void OnPDP_Request_Repeat_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnPDP_Request_Repeat_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RADIO_Status
        {
            get
            {
                return _RADIO_Status;
            }
            set
            {
                OnRADIO_StatusChanging(value);
                ReportPropertyChanging("RADIO_Status");
                _RADIO_Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RADIO_Status");
                OnRADIO_StatusChanged();
            }
        }
        private Nullable<global::System.Int32> _RADIO_Status;
        partial void OnRADIO_StatusChanging(Nullable<global::System.Int32> value);
        partial void OnRADIO_StatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RADIO_Status_delayFirst
        {
            get
            {
                return _RADIO_Status_delayFirst;
            }
            set
            {
                OnRADIO_Status_delayFirstChanging(value);
                ReportPropertyChanging("RADIO_Status_delayFirst");
                _RADIO_Status_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RADIO_Status_delayFirst");
                OnRADIO_Status_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _RADIO_Status_delayFirst;
        partial void OnRADIO_Status_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnRADIO_Status_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Radio_Cause
        {
            get
            {
                return _Radio_Cause;
            }
            set
            {
                OnRadio_CauseChanging(value);
                ReportPropertyChanging("Radio_Cause");
                _Radio_Cause = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Radio_Cause");
                OnRadio_CauseChanged();
            }
        }
        private global::System.String _Radio_Cause;
        partial void OnRadio_CauseChanging(global::System.String value);
        partial void OnRadio_CauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LLC_Discarded
        {
            get
            {
                return _LLC_Discarded;
            }
            set
            {
                OnLLC_DiscardedChanging(value);
                ReportPropertyChanging("LLC_Discarded");
                _LLC_Discarded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LLC_Discarded");
                OnLLC_DiscardedChanged();
            }
        }
        private Nullable<global::System.Int32> _LLC_Discarded;
        partial void OnLLC_DiscardedChanging(Nullable<global::System.Int32> value);
        partial void OnLLC_DiscardedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LLC_Discarded_delayFirst
        {
            get
            {
                return _LLC_Discarded_delayFirst;
            }
            set
            {
                OnLLC_Discarded_delayFirstChanging(value);
                ReportPropertyChanging("LLC_Discarded_delayFirst");
                _LLC_Discarded_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LLC_Discarded_delayFirst");
                OnLLC_Discarded_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _LLC_Discarded_delayFirst;
        partial void OnLLC_Discarded_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnLLC_Discarded_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Octets_Affected
        {
            get
            {
                return _Octets_Affected;
            }
            set
            {
                OnOctets_AffectedChanging(value);
                ReportPropertyChanging("Octets_Affected");
                _Octets_Affected = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Octets_Affected");
                OnOctets_AffectedChanged();
            }
        }
        private global::System.String _Octets_Affected;
        partial void OnOctets_AffectedChanging(global::System.String value);
        partial void OnOctets_AffectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDP_Act_Reject
        {
            get
            {
                return _PDP_Act_Reject;
            }
            set
            {
                OnPDP_Act_RejectChanging(value);
                ReportPropertyChanging("PDP_Act_Reject");
                _PDP_Act_Reject = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDP_Act_Reject");
                OnPDP_Act_RejectChanged();
            }
        }
        private Nullable<global::System.Int32> _PDP_Act_Reject;
        partial void OnPDP_Act_RejectChanging(Nullable<global::System.Int32> value);
        partial void OnPDP_Act_RejectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDP_Act_Reject_delayFirst
        {
            get
            {
                return _PDP_Act_Reject_delayFirst;
            }
            set
            {
                OnPDP_Act_Reject_delayFirstChanging(value);
                ReportPropertyChanging("PDP_Act_Reject_delayFirst");
                _PDP_Act_Reject_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDP_Act_Reject_delayFirst");
                OnPDP_Act_Reject_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _PDP_Act_Reject_delayFirst;
        partial void OnPDP_Act_Reject_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnPDP_Act_Reject_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reject_Cause
        {
            get
            {
                return _Reject_Cause;
            }
            set
            {
                OnReject_CauseChanging(value);
                ReportPropertyChanging("Reject_Cause");
                _Reject_Cause = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reject_Cause");
                OnReject_CauseChanged();
            }
        }
        private global::System.String _Reject_Cause;
        partial void OnReject_CauseChanging(global::System.String value);
        partial void OnReject_CauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reject_IMSI
        {
            get
            {
                return _Reject_IMSI;
            }
            set
            {
                OnReject_IMSIChanging(value);
                ReportPropertyChanging("Reject_IMSI");
                _Reject_IMSI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reject_IMSI");
                OnReject_IMSIChanged();
            }
        }
        private global::System.String _Reject_IMSI;
        partial void OnReject_IMSIChanging(global::System.String value);
        partial void OnReject_IMSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reject_BVCI
        {
            get
            {
                return _Reject_BVCI;
            }
            set
            {
                OnReject_BVCIChanging(value);
                ReportPropertyChanging("Reject_BVCI");
                _Reject_BVCI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reject_BVCI");
                OnReject_BVCIChanged();
            }
        }
        private global::System.String _Reject_BVCI;
        partial void OnReject_BVCIChanging(global::System.String value);
        partial void OnReject_BVCIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Detach_Request
        {
            get
            {
                return _Detach_Request;
            }
            set
            {
                OnDetach_RequestChanging(value);
                ReportPropertyChanging("Detach_Request");
                _Detach_Request = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Detach_Request");
                OnDetach_RequestChanged();
            }
        }
        private Nullable<global::System.Int32> _Detach_Request;
        partial void OnDetach_RequestChanging(Nullable<global::System.Int32> value);
        partial void OnDetach_RequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Detach_Request_delayFirst
        {
            get
            {
                return _Detach_Request_delayFirst;
            }
            set
            {
                OnDetach_Request_delayFirstChanging(value);
                ReportPropertyChanging("Detach_Request_delayFirst");
                _Detach_Request_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Detach_Request_delayFirst");
                OnDetach_Request_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _Detach_Request_delayFirst;
        partial void OnDetach_Request_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnDetach_Request_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> U_Exchange_identification
        {
            get
            {
                return _U_Exchange_identification;
            }
            set
            {
                OnU_Exchange_identificationChanging(value);
                ReportPropertyChanging("U_Exchange_identification");
                _U_Exchange_identification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Exchange_identification");
                OnU_Exchange_identificationChanged();
            }
        }
        private Nullable<global::System.Int32> _U_Exchange_identification;
        partial void OnU_Exchange_identificationChanging(Nullable<global::System.Int32> value);
        partial void OnU_Exchange_identificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> U_Exchange_identification_delayFirst
        {
            get
            {
                return _U_Exchange_identification_delayFirst;
            }
            set
            {
                OnU_Exchange_identification_delayFirstChanging(value);
                ReportPropertyChanging("U_Exchange_identification_delayFirst");
                _U_Exchange_identification_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Exchange_identification_delayFirst");
                OnU_Exchange_identification_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _U_Exchange_identification_delayFirst;
        partial void OnU_Exchange_identification_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnU_Exchange_identification_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U_Exchange_identification_timeFirst
        {
            get
            {
                return _U_Exchange_identification_timeFirst;
            }
            set
            {
                OnU_Exchange_identification_timeFirstChanging(value);
                ReportPropertyChanging("U_Exchange_identification_timeFirst");
                _U_Exchange_identification_timeFirst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U_Exchange_identification_timeFirst");
                OnU_Exchange_identification_timeFirstChanged();
            }
        }
        private global::System.String _U_Exchange_identification_timeFirst;
        partial void OnU_Exchange_identification_timeFirstChanging(global::System.String value);
        partial void OnU_Exchange_identification_timeFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bssgp_direction
        {
            get
            {
                return _bssgp_direction;
            }
            set
            {
                Onbssgp_directionChanging(value);
                ReportPropertyChanging("bssgp_direction");
                _bssgp_direction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bssgp_direction");
                Onbssgp_directionChanged();
            }
        }
        private global::System.String _bssgp_direction;
        partial void Onbssgp_directionChanging(global::System.String value);
        partial void Onbssgp_directionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1type
        {
            get
            {
                return _llcgprs_xid1type;
            }
            set
            {
                Onllcgprs_xid1typeChanging(value);
                ReportPropertyChanging("llcgprs_xid1type");
                _llcgprs_xid1type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1type");
                Onllcgprs_xid1typeChanged();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1type;
        partial void Onllcgprs_xid1typeChanging(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1byte1
        {
            get
            {
                return _llcgprs_xid1byte1;
            }
            set
            {
                Onllcgprs_xid1byte1Changing(value);
                ReportPropertyChanging("llcgprs_xid1byte1");
                _llcgprs_xid1byte1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1byte1");
                Onllcgprs_xid1byte1Changed();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1byte1;
        partial void Onllcgprs_xid1byte1Changing(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1byte1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1byte2
        {
            get
            {
                return _llcgprs_xid1byte2;
            }
            set
            {
                Onllcgprs_xid1byte2Changing(value);
                ReportPropertyChanging("llcgprs_xid1byte2");
                _llcgprs_xid1byte2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1byte2");
                Onllcgprs_xid1byte2Changed();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1byte2;
        partial void Onllcgprs_xid1byte2Changing(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1byte2Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GnModel2", Name="Gb_XID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gb_XID : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gb_XID object.
        /// </summary>
        /// <param name="fileNum">Initial value of the FileNum property.</param>
        /// <param name="packetNum">Initial value of the PacketNum property.</param>
        public static Gb_XID CreateGb_XID(global::System.Int32 fileNum, global::System.Int32 packetNum)
        {
            Gb_XID gb_XID = new Gb_XID();
            gb_XID.FileNum = fileNum;
            gb_XID.PacketNum = packetNum;
            return gb_XID;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileNum
        {
            get
            {
                return _FileNum;
            }
            set
            {
                if (_FileNum != value)
                {
                    OnFileNumChanging(value);
                    ReportPropertyChanging("FileNum");
                    _FileNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileNum");
                    OnFileNumChanged();
                }
            }
        }
        private global::System.Int32 _FileNum;
        partial void OnFileNumChanging(global::System.Int32 value);
        partial void OnFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PacketNum
        {
            get
            {
                return _PacketNum;
            }
            set
            {
                if (_PacketNum != value)
                {
                    OnPacketNumChanging(value);
                    ReportPropertyChanging("PacketNum");
                    _PacketNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PacketNum");
                    OnPacketNumChanged();
                }
            }
        }
        private global::System.Int32 _PacketNum;
        partial void OnPacketNumChanging(global::System.Int32 value);
        partial void OnPacketNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFileNum
        {
            get
            {
                return _BeginFileNum;
            }
            set
            {
                OnBeginFileNumChanging(value);
                ReportPropertyChanging("BeginFileNum");
                _BeginFileNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFileNum");
                OnBeginFileNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFileNum;
        partial void OnBeginFileNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFrameNum
        {
            get
            {
                return _BeginFrameNum;
            }
            set
            {
                OnBeginFrameNumChanging(value);
                ReportPropertyChanging("BeginFrameNum");
                _BeginFrameNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFrameNum");
                OnBeginFrameNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFrameNum;
        partial void OnBeginFrameNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFrameNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PacketTime
        {
            get
            {
                return _PacketTime;
            }
            set
            {
                OnPacketTimeChanging(value);
                ReportPropertyChanging("PacketTime");
                _PacketTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime");
                OnPacketTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PacketTime;
        partial void OnPacketTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPacketTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PacketTime_ms_
        {
            get
            {
                return _PacketTime_ms_;
            }
            set
            {
                OnPacketTime_ms_Changing(value);
                ReportPropertyChanging("PacketTime_ms_");
                _PacketTime_ms_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime_ms_");
                OnPacketTime_ms_Changed();
            }
        }
        private Nullable<global::System.Int32> _PacketTime_ms_;
        partial void OnPacketTime_ms_Changing(Nullable<global::System.Int32> value);
        partial void OnPacketTime_ms_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DumpFor
        {
            get
            {
                return _DumpFor;
            }
            set
            {
                OnDumpForChanging(value);
                ReportPropertyChanging("DumpFor");
                _DumpFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DumpFor");
                OnDumpForChanged();
            }
        }
        private global::System.String _DumpFor;
        partial void OnDumpForChanging(global::System.String value);
        partial void OnDumpForChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> U_Exchange_identification
        {
            get
            {
                return _U_Exchange_identification;
            }
            set
            {
                OnU_Exchange_identificationChanging(value);
                ReportPropertyChanging("U_Exchange_identification");
                _U_Exchange_identification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Exchange_identification");
                OnU_Exchange_identificationChanged();
            }
        }
        private Nullable<global::System.Int32> _U_Exchange_identification;
        partial void OnU_Exchange_identificationChanging(Nullable<global::System.Int32> value);
        partial void OnU_Exchange_identificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bssgp_direction
        {
            get
            {
                return _bssgp_direction;
            }
            set
            {
                Onbssgp_directionChanging(value);
                ReportPropertyChanging("bssgp_direction");
                _bssgp_direction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bssgp_direction");
                Onbssgp_directionChanged();
            }
        }
        private global::System.String _bssgp_direction;
        partial void Onbssgp_directionChanging(global::System.String value);
        partial void Onbssgp_directionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1type
        {
            get
            {
                return _llcgprs_xid1type;
            }
            set
            {
                Onllcgprs_xid1typeChanging(value);
                ReportPropertyChanging("llcgprs_xid1type");
                _llcgprs_xid1type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1type");
                Onllcgprs_xid1typeChanged();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1type;
        partial void Onllcgprs_xid1typeChanging(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1byte1
        {
            get
            {
                return _llcgprs_xid1byte1;
            }
            set
            {
                Onllcgprs_xid1byte1Changing(value);
                ReportPropertyChanging("llcgprs_xid1byte1");
                _llcgprs_xid1byte1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1byte1");
                Onllcgprs_xid1byte1Changed();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1byte1;
        partial void Onllcgprs_xid1byte1Changing(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1byte1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> llcgprs_xid1byte2
        {
            get
            {
                return _llcgprs_xid1byte2;
            }
            set
            {
                Onllcgprs_xid1byte2Changing(value);
                ReportPropertyChanging("llcgprs_xid1byte2");
                _llcgprs_xid1byte2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llcgprs_xid1byte2");
                Onllcgprs_xid1byte2Changed();
            }
        }
        private Nullable<global::System.Int32> _llcgprs_xid1byte2;
        partial void Onllcgprs_xid1byte2Changing(Nullable<global::System.Int32> value);
        partial void Onllcgprs_xid1byte2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> U_Exchange_identification1
        {
            get
            {
                return _U_Exchange_identification1;
            }
            set
            {
                OnU_Exchange_identification1Changing(value);
                ReportPropertyChanging("U_Exchange_identification1");
                _U_Exchange_identification1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Exchange_identification1");
                OnU_Exchange_identification1Changed();
            }
        }
        private Nullable<global::System.Int32> _U_Exchange_identification1;
        partial void OnU_Exchange_identification1Changing(Nullable<global::System.Int32> value);
        partial void OnU_Exchange_identification1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> U_Exchange_identification1_delayFirst
        {
            get
            {
                return _U_Exchange_identification1_delayFirst;
            }
            set
            {
                OnU_Exchange_identification1_delayFirstChanging(value);
                ReportPropertyChanging("U_Exchange_identification1_delayFirst");
                _U_Exchange_identification1_delayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Exchange_identification1_delayFirst");
                OnU_Exchange_identification1_delayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _U_Exchange_identification1_delayFirst;
        partial void OnU_Exchange_identification1_delayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnU_Exchange_identification1_delayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C1bssgp_direction
        {
            get
            {
                return _C1bssgp_direction;
            }
            set
            {
                OnC1bssgp_directionChanging(value);
                ReportPropertyChanging("C1bssgp_direction");
                _C1bssgp_direction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C1bssgp_direction");
                OnC1bssgp_directionChanged();
            }
        }
        private global::System.String _C1bssgp_direction;
        partial void OnC1bssgp_directionChanging(global::System.String value);
        partial void OnC1bssgp_directionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C1llcgprs_xid1type
        {
            get
            {
                return _C1llcgprs_xid1type;
            }
            set
            {
                OnC1llcgprs_xid1typeChanging(value);
                ReportPropertyChanging("C1llcgprs_xid1type");
                _C1llcgprs_xid1type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C1llcgprs_xid1type");
                OnC1llcgprs_xid1typeChanged();
            }
        }
        private Nullable<global::System.Int32> _C1llcgprs_xid1type;
        partial void OnC1llcgprs_xid1typeChanging(Nullable<global::System.Int32> value);
        partial void OnC1llcgprs_xid1typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C1llcgprs_xid1byte1
        {
            get
            {
                return _C1llcgprs_xid1byte1;
            }
            set
            {
                OnC1llcgprs_xid1byte1Changing(value);
                ReportPropertyChanging("C1llcgprs_xid1byte1");
                _C1llcgprs_xid1byte1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C1llcgprs_xid1byte1");
                OnC1llcgprs_xid1byte1Changed();
            }
        }
        private Nullable<global::System.Int32> _C1llcgprs_xid1byte1;
        partial void OnC1llcgprs_xid1byte1Changing(Nullable<global::System.Int32> value);
        partial void OnC1llcgprs_xid1byte1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C1llcgprs_xid1byte2
        {
            get
            {
                return _C1llcgprs_xid1byte2;
            }
            set
            {
                OnC1llcgprs_xid1byte2Changing(value);
                ReportPropertyChanging("C1llcgprs_xid1byte2");
                _C1llcgprs_xid1byte2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C1llcgprs_xid1byte2");
                OnC1llcgprs_xid1byte2Changed();
            }
        }
        private Nullable<global::System.Int32> _C1llcgprs_xid1byte2;
        partial void OnC1llcgprs_xid1byte2Changing(Nullable<global::System.Int32> value);
        partial void OnC1llcgprs_xid1byte2Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GnModel2", Name="imeitype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class imeitype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new imeitype object.
        /// </summary>
        /// <param name="imei">Initial value of the imei property.</param>
        public static imeitype Createimeitype(global::System.String imei)
        {
            imeitype imeitype = new imeitype();
            imeitype.imei = imei;
            return imeitype;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imei
        {
            get
            {
                return _imei;
            }
            set
            {
                if (_imei != value)
                {
                    OnimeiChanging(value);
                    ReportPropertyChanging("imei");
                    _imei = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("imei");
                    OnimeiChanged();
                }
            }
        }
        private global::System.String _imei;
        partial void OnimeiChanging(global::System.String value);
        partial void OnimeiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imeifactory
        {
            get
            {
                return _imeifactory;
            }
            set
            {
                OnimeifactoryChanging(value);
                ReportPropertyChanging("imeifactory");
                _imeifactory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imeifactory");
                OnimeifactoryChanged();
            }
        }
        private global::System.String _imeifactory;
        partial void OnimeifactoryChanging(global::System.String value);
        partial void OnimeifactoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imeiname
        {
            get
            {
                return _imeiname;
            }
            set
            {
                OnimeinameChanging(value);
                ReportPropertyChanging("imeiname");
                _imeiname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imeiname");
                OnimeinameChanged();
            }
        }
        private global::System.String _imeiname;
        partial void OnimeinameChanging(global::System.String value);
        partial void OnimeinameChanged();

        #endregion
    
    }

    #endregion
    
}
