//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GnPlatForm.SqlServer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GuangZhou_GnEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GuangZhou_GnEntities object using the connection string found in the 'GuangZhou_GnEntities' section of the application configuration file.
        /// </summary>
        public GuangZhou_GnEntities() : base("name=GuangZhou_GnEntities", "GuangZhou_GnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities object.
        /// </summary>
        public GuangZhou_GnEntities(string connectionString) : base(connectionString, "GuangZhou_GnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities object.
        /// </summary>
        public GuangZhou_GnEntities(EntityConnection connection) : base(connection, "GuangZhou_GnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mpos_gn_common> mpos_gn_common
        {
            get
            {
                if ((_mpos_gn_common == null))
                {
                    _mpos_gn_common = base.CreateObjectSet<mpos_gn_common>("mpos_gn_common");
                }
                return _mpos_gn_common;
            }
        }
        private ObjectSet<mpos_gn_common> _mpos_gn_common;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mpos_gn_common EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTompos_gn_common(mpos_gn_common mpos_gn_common)
        {
            base.AddObject("mpos_gn_common", mpos_gn_common);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GnModel", Name="mpos_gn_common")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mpos_gn_common : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mpos_gn_common object.
        /// </summary>
        /// <param name="gn_id">Initial value of the gn_id property.</param>
        public static mpos_gn_common Creatempos_gn_common(global::System.Int32 gn_id)
        {
            mpos_gn_common mpos_gn_common = new mpos_gn_common();
            mpos_gn_common.gn_id = gn_id;
            return mpos_gn_common;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gn_id
        {
            get
            {
                return _gn_id;
            }
            set
            {
                if (_gn_id != value)
                {
                    Ongn_idChanging(value);
                    ReportPropertyChanging("gn_id");
                    _gn_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gn_id");
                    Ongn_idChanged();
                }
            }
        }
        private global::System.Int32 _gn_id;
        partial void Ongn_idChanging(global::System.Int32 value);
        partial void Ongn_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Online_ID
        {
            get
            {
                return _Online_ID;
            }
            set
            {
                OnOnline_IDChanging(value);
                ReportPropertyChanging("Online_ID");
                _Online_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Online_ID");
                OnOnline_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _Online_ID;
        partial void OnOnline_IDChanging(Nullable<global::System.Int64> value);
        partial void OnOnline_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Session_ID
        {
            get
            {
                return _Session_ID;
            }
            set
            {
                OnSession_IDChanging(value);
                ReportPropertyChanging("Session_ID");
                _Session_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Session_ID");
                OnSession_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _Session_ID;
        partial void OnSession_IDChanging(Nullable<global::System.Int64> value);
        partial void OnSession_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Start_Date_Time
        {
            get
            {
                return _Start_Date_Time;
            }
            set
            {
                OnStart_Date_TimeChanging(value);
                ReportPropertyChanging("Start_Date_Time");
                _Start_Date_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start_Date_Time");
                OnStart_Date_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Start_Date_Time;
        partial void OnStart_Date_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStart_Date_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> End_Date_Time
        {
            get
            {
                return _End_Date_Time;
            }
            set
            {
                OnEnd_Date_TimeChanging(value);
                ReportPropertyChanging("End_Date_Time");
                _End_Date_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End_Date_Time");
                OnEnd_Date_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _End_Date_Time;
        partial void OnEnd_Date_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEnd_Date_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SGSN_IP
        {
            get
            {
                return _SGSN_IP;
            }
            set
            {
                OnSGSN_IPChanging(value);
                ReportPropertyChanging("SGSN_IP");
                _SGSN_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGSN_IP");
                OnSGSN_IPChanged();
            }
        }
        private Nullable<global::System.Int64> _SGSN_IP;
        partial void OnSGSN_IPChanging(Nullable<global::System.Int64> value);
        partial void OnSGSN_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SGSN
        {
            get
            {
                return _SGSN;
            }
            set
            {
                OnSGSNChanging(value);
                ReportPropertyChanging("SGSN");
                _SGSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SGSN");
                OnSGSNChanged();
            }
        }
        private global::System.String _SGSN;
        partial void OnSGSNChanging(global::System.String value);
        partial void OnSGSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GGSN_IP
        {
            get
            {
                return _GGSN_IP;
            }
            set
            {
                OnGGSN_IPChanging(value);
                ReportPropertyChanging("GGSN_IP");
                _GGSN_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GGSN_IP");
                OnGGSN_IPChanged();
            }
        }
        private Nullable<global::System.Int64> _GGSN_IP;
        partial void OnGGSN_IPChanging(Nullable<global::System.Int64> value);
        partial void OnGGSN_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GGSN
        {
            get
            {
                return _GGSN;
            }
            set
            {
                OnGGSNChanging(value);
                ReportPropertyChanging("GGSN");
                _GGSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GGSN");
                OnGGSNChanged();
            }
        }
        private global::System.String _GGSN;
        partial void OnGGSNChanging(global::System.String value);
        partial void OnGGSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LAC
        {
            get
            {
                return _LAC;
            }
            set
            {
                OnLACChanging(value);
                ReportPropertyChanging("LAC");
                _LAC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAC");
                OnLACChanged();
            }
        }
        private Nullable<global::System.Int32> _LAC;
        partial void OnLACChanging(Nullable<global::System.Int32> value);
        partial void OnLACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CI
        {
            get
            {
                return _CI;
            }
            set
            {
                OnCIChanging(value);
                ReportPropertyChanging("CI");
                _CI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CI");
                OnCIChanged();
            }
        }
        private Nullable<global::System.Int32> _CI;
        partial void OnCIChanging(Nullable<global::System.Int32> value);
        partial void OnCIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SAC
        {
            get
            {
                return _SAC;
            }
            set
            {
                OnSACChanging(value);
                ReportPropertyChanging("SAC");
                _SAC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SAC");
                OnSACChanged();
            }
        }
        private Nullable<global::System.Int32> _SAC;
        partial void OnSACChanging(Nullable<global::System.Int32> value);
        partial void OnSACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMSI
        {
            get
            {
                return _IMSI;
            }
            set
            {
                OnIMSIChanging(value);
                ReportPropertyChanging("IMSI");
                _IMSI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMSI");
                OnIMSIChanged();
            }
        }
        private global::System.String _IMSI;
        partial void OnIMSIChanging(global::System.String value);
        partial void OnIMSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private global::System.String _IMEI;
        partial void OnIMEIChanging(global::System.String value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prefix_IMEI
        {
            get
            {
                return _Prefix_IMEI;
            }
            set
            {
                OnPrefix_IMEIChanging(value);
                ReportPropertyChanging("Prefix_IMEI");
                _Prefix_IMEI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prefix_IMEI");
                OnPrefix_IMEIChanged();
            }
        }
        private global::System.String _Prefix_IMEI;
        partial void OnPrefix_IMEIChanging(global::System.String value);
        partial void OnPrefix_IMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MSISDN
        {
            get
            {
                return _MSISDN;
            }
            set
            {
                OnMSISDNChanging(value);
                ReportPropertyChanging("MSISDN");
                _MSISDN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MSISDN");
                OnMSISDNChanged();
            }
        }
        private Nullable<global::System.Int64> _MSISDN;
        partial void OnMSISDNChanging(Nullable<global::System.Int64> value);
        partial void OnMSISDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APN
        {
            get
            {
                return _APN;
            }
            set
            {
                OnAPNChanging(value);
                ReportPropertyChanging("APN");
                _APN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APN");
                OnAPNChanged();
            }
        }
        private global::System.String _APN;
        partial void OnAPNChanging(global::System.String value);
        partial void OnAPNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RAT_TYPE
        {
            get
            {
                return _RAT_TYPE;
            }
            set
            {
                OnRAT_TYPEChanging(value);
                ReportPropertyChanging("RAT_TYPE");
                _RAT_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RAT_TYPE");
                OnRAT_TYPEChanged();
            }
        }
        private Nullable<global::System.Int32> _RAT_TYPE;
        partial void OnRAT_TYPEChanging(Nullable<global::System.Int32> value);
        partial void OnRAT_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_RAT_TYPE
        {
            get
            {
                return _my_RAT_TYPE;
            }
            set
            {
                Onmy_RAT_TYPEChanging(value);
                ReportPropertyChanging("my_RAT_TYPE");
                _my_RAT_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_RAT_TYPE");
                Onmy_RAT_TYPEChanged();
            }
        }
        private global::System.String _my_RAT_TYPE;
        partial void Onmy_RAT_TYPEChanging(global::System.String value);
        partial void Onmy_RAT_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PROTOCOL
        {
            get
            {
                return _PROTOCOL;
            }
            set
            {
                OnPROTOCOLChanging(value);
                ReportPropertyChanging("PROTOCOL");
                _PROTOCOL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROTOCOL");
                OnPROTOCOLChanged();
            }
        }
        private Nullable<global::System.Int32> _PROTOCOL;
        partial void OnPROTOCOLChanging(Nullable<global::System.Int32> value);
        partial void OnPROTOCOLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Protocol
        {
            get
            {
                return _my_Protocol;
            }
            set
            {
                Onmy_ProtocolChanging(value);
                ReportPropertyChanging("my_Protocol");
                _my_Protocol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Protocol");
                Onmy_ProtocolChanged();
            }
        }
        private global::System.String _my_Protocol;
        partial void Onmy_ProtocolChanging(global::System.String value);
        partial void Onmy_ProtocolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Event_Type
        {
            get
            {
                return _Event_Type;
            }
            set
            {
                OnEvent_TypeChanging(value);
                ReportPropertyChanging("Event_Type");
                _Event_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Event_Type");
                OnEvent_TypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Event_Type;
        partial void OnEvent_TypeChanging(Nullable<global::System.Int32> value);
        partial void OnEvent_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Event_Type
        {
            get
            {
                return _my_Event_Type;
            }
            set
            {
                Onmy_Event_TypeChanging(value);
                ReportPropertyChanging("my_Event_Type");
                _my_Event_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Event_Type");
                Onmy_Event_TypeChanged();
            }
        }
        private global::System.String _my_Event_Type;
        partial void Onmy_Event_TypeChanging(global::System.String value);
        partial void Onmy_Event_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IP_LEN_UL
        {
            get
            {
                return _IP_LEN_UL;
            }
            set
            {
                OnIP_LEN_ULChanging(value);
                ReportPropertyChanging("IP_LEN_UL");
                _IP_LEN_UL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP_LEN_UL");
                OnIP_LEN_ULChanged();
            }
        }
        private Nullable<global::System.Int32> _IP_LEN_UL;
        partial void OnIP_LEN_ULChanging(Nullable<global::System.Int32> value);
        partial void OnIP_LEN_ULChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IP_LEN_DL
        {
            get
            {
                return _IP_LEN_DL;
            }
            set
            {
                OnIP_LEN_DLChanging(value);
                ReportPropertyChanging("IP_LEN_DL");
                _IP_LEN_DL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP_LEN_DL");
                OnIP_LEN_DLChanged();
            }
        }
        private Nullable<global::System.Int32> _IP_LEN_DL;
        partial void OnIP_LEN_DLChanging(Nullable<global::System.Int32> value);
        partial void OnIP_LEN_DLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count_Packet_UL
        {
            get
            {
                return _Count_Packet_UL;
            }
            set
            {
                OnCount_Packet_ULChanging(value);
                ReportPropertyChanging("Count_Packet_UL");
                _Count_Packet_UL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count_Packet_UL");
                OnCount_Packet_ULChanged();
            }
        }
        private Nullable<global::System.Int32> _Count_Packet_UL;
        partial void OnCount_Packet_ULChanging(Nullable<global::System.Int32> value);
        partial void OnCount_Packet_ULChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count_Packet_DL
        {
            get
            {
                return _Count_Packet_DL;
            }
            set
            {
                OnCount_Packet_DLChanging(value);
                ReportPropertyChanging("Count_Packet_DL");
                _Count_Packet_DL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count_Packet_DL");
                OnCount_Packet_DLChanged();
            }
        }
        private Nullable<global::System.Int32> _Count_Packet_DL;
        partial void OnCount_Packet_DLChanging(Nullable<global::System.Int32> value);
        partial void OnCount_Packet_DLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.Decimal> _Duration;
        partial void OnDurationChanging(Nullable<global::System.Decimal> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SOURCE_IP
        {
            get
            {
                return _SOURCE_IP;
            }
            set
            {
                OnSOURCE_IPChanging(value);
                ReportPropertyChanging("SOURCE_IP");
                _SOURCE_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOURCE_IP");
                OnSOURCE_IPChanged();
            }
        }
        private Nullable<global::System.Int64> _SOURCE_IP;
        partial void OnSOURCE_IPChanging(Nullable<global::System.Int64> value);
        partial void OnSOURCE_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_SOURCE_IP
        {
            get
            {
                return _my_SOURCE_IP;
            }
            set
            {
                Onmy_SOURCE_IPChanging(value);
                ReportPropertyChanging("my_SOURCE_IP");
                _my_SOURCE_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_SOURCE_IP");
                Onmy_SOURCE_IPChanged();
            }
        }
        private global::System.String _my_SOURCE_IP;
        partial void Onmy_SOURCE_IPChanging(global::System.String value);
        partial void Onmy_SOURCE_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DEST_IP
        {
            get
            {
                return _DEST_IP;
            }
            set
            {
                OnDEST_IPChanging(value);
                ReportPropertyChanging("DEST_IP");
                _DEST_IP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEST_IP");
                OnDEST_IPChanged();
            }
        }
        private Nullable<global::System.Int64> _DEST_IP;
        partial void OnDEST_IPChanging(Nullable<global::System.Int64> value);
        partial void OnDEST_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_DEST_IP
        {
            get
            {
                return _my_DEST_IP;
            }
            set
            {
                Onmy_DEST_IPChanging(value);
                ReportPropertyChanging("my_DEST_IP");
                _my_DEST_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_DEST_IP");
                Onmy_DEST_IPChanged();
            }
        }
        private global::System.String _my_DEST_IP;
        partial void Onmy_DEST_IPChanging(global::System.String value);
        partial void Onmy_DEST_IPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOURCE_PORT
        {
            get
            {
                return _SOURCE_PORT;
            }
            set
            {
                OnSOURCE_PORTChanging(value);
                ReportPropertyChanging("SOURCE_PORT");
                _SOURCE_PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOURCE_PORT");
                OnSOURCE_PORTChanged();
            }
        }
        private Nullable<global::System.Int32> _SOURCE_PORT;
        partial void OnSOURCE_PORTChanging(Nullable<global::System.Int32> value);
        partial void OnSOURCE_PORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DEST_PORT
        {
            get
            {
                return _DEST_PORT;
            }
            set
            {
                OnDEST_PORTChanging(value);
                ReportPropertyChanging("DEST_PORT");
                _DEST_PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEST_PORT");
                OnDEST_PORTChanged();
            }
        }
        private Nullable<global::System.Int32> _DEST_PORT;
        partial void OnDEST_PORTChanging(Nullable<global::System.Int32> value);
        partial void OnDEST_PORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URI
        {
            get
            {
                return _URI;
            }
            set
            {
                OnURIChanging(value);
                ReportPropertyChanging("URI");
                _URI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URI");
                OnURIChanged();
            }
        }
        private global::System.String _URI;
        partial void OnURIChanging(global::System.String value);
        partial void OnURIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> my_URI_Len
        {
            get
            {
                return _my_URI_Len;
            }
            set
            {
                Onmy_URI_LenChanging(value);
                ReportPropertyChanging("my_URI_Len");
                _my_URI_Len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("my_URI_Len");
                Onmy_URI_LenChanged();
            }
        }
        private Nullable<global::System.Int32> _my_URI_Len;
        partial void Onmy_URI_LenChanging(Nullable<global::System.Int32> value);
        partial void Onmy_URI_LenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_IMEI
        {
            get
            {
                return _my_URI_IMEI;
            }
            set
            {
                Onmy_URI_IMEIChanging(value);
                ReportPropertyChanging("my_URI_IMEI");
                _my_URI_IMEI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_IMEI");
                Onmy_URI_IMEIChanged();
            }
        }
        private global::System.String _my_URI_IMEI;
        partial void Onmy_URI_IMEIChanging(global::System.String value);
        partial void Onmy_URI_IMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_UA
        {
            get
            {
                return _my_URI_UA;
            }
            set
            {
                Onmy_URI_UAChanging(value);
                ReportPropertyChanging("my_URI_UA");
                _my_URI_UA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_UA");
                Onmy_URI_UAChanged();
            }
        }
        private global::System.String _my_URI_UA;
        partial void Onmy_URI_UAChanging(global::System.String value);
        partial void Onmy_URI_UAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_UA_MS_Type
        {
            get
            {
                return _my_URI_UA_MS_Type;
            }
            set
            {
                Onmy_URI_UA_MS_TypeChanging(value);
                ReportPropertyChanging("my_URI_UA_MS_Type");
                _my_URI_UA_MS_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_UA_MS_Type");
                Onmy_URI_UA_MS_TypeChanged();
            }
        }
        private global::System.String _my_URI_UA_MS_Type;
        partial void Onmy_URI_UA_MS_TypeChanging(global::System.String value);
        partial void Onmy_URI_UA_MS_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_UA_Weibo_Ver
        {
            get
            {
                return _my_URI_UA_Weibo_Ver;
            }
            set
            {
                Onmy_URI_UA_Weibo_VerChanging(value);
                ReportPropertyChanging("my_URI_UA_Weibo_Ver");
                _my_URI_UA_Weibo_Ver = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_UA_Weibo_Ver");
                Onmy_URI_UA_Weibo_VerChanged();
            }
        }
        private global::System.String _my_URI_UA_Weibo_Ver;
        partial void Onmy_URI_UA_Weibo_VerChanging(global::System.String value);
        partial void Onmy_URI_UA_Weibo_VerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_UA_OS
        {
            get
            {
                return _my_URI_UA_OS;
            }
            set
            {
                Onmy_URI_UA_OSChanging(value);
                ReportPropertyChanging("my_URI_UA_OS");
                _my_URI_UA_OS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_UA_OS");
                Onmy_URI_UA_OSChanged();
            }
        }
        private global::System.String _my_URI_UA_OS;
        partial void Onmy_URI_UA_OSChanging(global::System.String value);
        partial void Onmy_URI_UA_OSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URI_Main
        {
            get
            {
                return _URI_Main;
            }
            set
            {
                OnURI_MainChanging(value);
                ReportPropertyChanging("URI_Main");
                _URI_Main = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URI_Main");
                OnURI_MainChanged();
            }
        }
        private global::System.String _URI_Main;
        partial void OnURI_MainChanging(global::System.String value);
        partial void OnURI_MainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_Main
        {
            get
            {
                return _my_URI_Main;
            }
            set
            {
                Onmy_URI_MainChanging(value);
                ReportPropertyChanging("my_URI_Main");
                _my_URI_Main = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_Main");
                Onmy_URI_MainChanged();
            }
        }
        private global::System.String _my_URI_Main;
        partial void Onmy_URI_MainChanging(global::System.String value);
        partial void Onmy_URI_MainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_URI_Main_header
        {
            get
            {
                return _my_URI_Main_header;
            }
            set
            {
                Onmy_URI_Main_headerChanging(value);
                ReportPropertyChanging("my_URI_Main_header");
                _my_URI_Main_header = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_URI_Main_header");
                Onmy_URI_Main_headerChanged();
            }
        }
        private global::System.String _my_URI_Main_header;
        partial void Onmy_URI_Main_headerChanging(global::System.String value);
        partial void Onmy_URI_Main_headerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content_Type
        {
            get
            {
                return _Content_Type;
            }
            set
            {
                OnContent_TypeChanging(value);
                ReportPropertyChanging("Content_Type");
                _Content_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content_Type");
                OnContent_TypeChanged();
            }
        }
        private global::System.String _Content_Type;
        partial void OnContent_TypeChanging(global::System.String value);
        partial void OnContent_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Content_Type
        {
            get
            {
                return _my_Content_Type;
            }
            set
            {
                Onmy_Content_TypeChanging(value);
                ReportPropertyChanging("my_Content_Type");
                _my_Content_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Content_Type");
                Onmy_Content_TypeChanged();
            }
        }
        private global::System.String _my_Content_Type;
        partial void Onmy_Content_TypeChanging(global::System.String value);
        partial void Onmy_Content_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User_Agent_Main
        {
            get
            {
                return _User_Agent_Main;
            }
            set
            {
                OnUser_Agent_MainChanging(value);
                ReportPropertyChanging("User_Agent_Main");
                _User_Agent_Main = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User_Agent_Main");
                OnUser_Agent_MainChanged();
            }
        }
        private global::System.String _User_Agent_Main;
        partial void OnUser_Agent_MainChanging(global::System.String value);
        partial void OnUser_Agent_MainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Service_TYPE
        {
            get
            {
                return _Service_TYPE;
            }
            set
            {
                OnService_TYPEChanging(value);
                ReportPropertyChanging("Service_TYPE");
                _Service_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Service_TYPE");
                OnService_TYPEChanged();
            }
        }
        private Nullable<global::System.Int32> _Service_TYPE;
        partial void OnService_TYPEChanging(Nullable<global::System.Int32> value);
        partial void OnService_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Service_TYPE
        {
            get
            {
                return _my_Service_TYPE;
            }
            set
            {
                Onmy_Service_TYPEChanging(value);
                ReportPropertyChanging("my_Service_TYPE");
                _my_Service_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Service_TYPE");
                Onmy_Service_TYPEChanged();
            }
        }
        private global::System.String _my_Service_TYPE;
        partial void Onmy_Service_TYPEChanging(global::System.String value);
        partial void Onmy_Service_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sub_Service_Type
        {
            get
            {
                return _Sub_Service_Type;
            }
            set
            {
                OnSub_Service_TypeChanging(value);
                ReportPropertyChanging("Sub_Service_Type");
                _Sub_Service_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sub_Service_Type");
                OnSub_Service_TypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Sub_Service_Type;
        partial void OnSub_Service_TypeChanging(Nullable<global::System.Int32> value);
        partial void OnSub_Service_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Sub_Service_Type
        {
            get
            {
                return _my_Sub_Service_Type;
            }
            set
            {
                Onmy_Sub_Service_TypeChanging(value);
                ReportPropertyChanging("my_Sub_Service_Type");
                _my_Sub_Service_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Sub_Service_Type");
                Onmy_Sub_Service_TypeChanged();
            }
        }
        private global::System.String _my_Sub_Service_Type;
        partial void Onmy_Sub_Service_TypeChanging(global::System.String value);
        partial void Onmy_Sub_Service_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsReassemble
        {
            get
            {
                return _IsReassemble;
            }
            set
            {
                OnIsReassembleChanging(value);
                ReportPropertyChanging("IsReassemble");
                _IsReassemble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReassemble");
                OnIsReassembleChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsReassemble;
        partial void OnIsReassembleChanging(Nullable<global::System.Boolean> value);
        partial void OnIsReassembleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Delete_PDP
        {
            get
            {
                return _Delete_PDP;
            }
            set
            {
                OnDelete_PDPChanging(value);
                ReportPropertyChanging("Delete_PDP");
                _Delete_PDP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delete_PDP");
                OnDelete_PDPChanged();
            }
        }
        private Nullable<global::System.Boolean> _Delete_PDP;
        partial void OnDelete_PDPChanging(Nullable<global::System.Boolean> value);
        partial void OnDelete_PDPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Delete_PDP_Direction
        {
            get
            {
                return _Delete_PDP_Direction;
            }
            set
            {
                OnDelete_PDP_DirectionChanging(value);
                ReportPropertyChanging("Delete_PDP_Direction");
                _Delete_PDP_Direction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delete_PDP_Direction");
                OnDelete_PDP_DirectionChanged();
            }
        }
        private Nullable<global::System.Boolean> _Delete_PDP_Direction;
        partial void OnDelete_PDP_DirectionChanging(Nullable<global::System.Boolean> value);
        partial void OnDelete_PDP_DirectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Abnormal_reason
        {
            get
            {
                return _Abnormal_reason;
            }
            set
            {
                OnAbnormal_reasonChanging(value);
                ReportPropertyChanging("Abnormal_reason");
                _Abnormal_reason = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Abnormal_reason");
                OnAbnormal_reasonChanged();
            }
        }
        private Nullable<global::System.Int32> _Abnormal_reason;
        partial void OnAbnormal_reasonChanging(Nullable<global::System.Int32> value);
        partial void OnAbnormal_reasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String my_Abnormal_reason
        {
            get
            {
                return _my_Abnormal_reason;
            }
            set
            {
                Onmy_Abnormal_reasonChanging(value);
                ReportPropertyChanging("my_Abnormal_reason");
                _my_Abnormal_reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("my_Abnormal_reason");
                Onmy_Abnormal_reasonChanged();
            }
        }
        private global::System.String _my_Abnormal_reason;
        partial void Onmy_Abnormal_reasonChanging(global::System.String value);
        partial void Onmy_Abnormal_reasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Repeat_Count
        {
            get
            {
                return _Repeat_Count;
            }
            set
            {
                OnRepeat_CountChanging(value);
                ReportPropertyChanging("Repeat_Count");
                _Repeat_Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Repeat_Count");
                OnRepeat_CountChanged();
            }
        }
        private Nullable<global::System.Int32> _Repeat_Count;
        partial void OnRepeat_CountChanging(Nullable<global::System.Int32> value);
        partial void OnRepeat_CountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Resp
        {
            get
            {
                return _Resp;
            }
            set
            {
                OnRespChanging(value);
                ReportPropertyChanging("Resp");
                _Resp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp");
                OnRespChanged();
            }
        }
        private Nullable<global::System.Boolean> _Resp;
        partial void OnRespChanging(Nullable<global::System.Boolean> value);
        partial void OnRespChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Resp_DelayFirst
        {
            get
            {
                return _Resp_DelayFirst;
            }
            set
            {
                OnResp_DelayFirstChanging(value);
                ReportPropertyChanging("Resp_DelayFirst");
                _Resp_DelayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp_DelayFirst");
                OnResp_DelayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _Resp_DelayFirst;
        partial void OnResp_DelayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnResp_DelayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Resp_cause
        {
            get
            {
                return _Resp_cause;
            }
            set
            {
                OnResp_causeChanging(value);
                ReportPropertyChanging("Resp_cause");
                _Resp_cause = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resp_cause");
                OnResp_causeChanged();
            }
        }
        private Nullable<global::System.Int32> _Resp_cause;
        partial void OnResp_causeChanging(Nullable<global::System.Int32> value);
        partial void OnResp_causeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> abort
        {
            get
            {
                return _abort;
            }
            set
            {
                OnabortChanging(value);
                ReportPropertyChanging("abort");
                _abort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("abort");
                OnabortChanged();
            }
        }
        private Nullable<global::System.Int32> _abort;
        partial void OnabortChanging(Nullable<global::System.Int32> value);
        partial void OnabortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Disconnect
        {
            get
            {
                return _Disconnect;
            }
            set
            {
                OnDisconnectChanging(value);
                ReportPropertyChanging("Disconnect");
                _Disconnect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Disconnect");
                OnDisconnectChanged();
            }
        }
        private Nullable<global::System.Boolean> _Disconnect;
        partial void OnDisconnectChanging(Nullable<global::System.Boolean> value);
        partial void OnDisconnectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Result
        {
            get
            {
                return _Result;
            }
            set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private Nullable<global::System.Boolean> _Result;
        partial void OnResultChanging(Nullable<global::System.Boolean> value);
        partial void OnResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Result_DelayFirst
        {
            get
            {
                return _Result_DelayFirst;
            }
            set
            {
                OnResult_DelayFirstChanging(value);
                ReportPropertyChanging("Result_DelayFirst");
                _Result_DelayFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result_DelayFirst");
                OnResult_DelayFirstChanged();
            }
        }
        private Nullable<global::System.Int32> _Result_DelayFirst;
        partial void OnResult_DelayFirstChanging(Nullable<global::System.Int32> value);
        partial void OnResult_DelayFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MMS_request
        {
            get
            {
                return _MMS_request;
            }
            set
            {
                OnMMS_requestChanging(value);
                ReportPropertyChanging("MMS_request");
                _MMS_request = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MMS_request");
                OnMMS_requestChanged();
            }
        }
        private Nullable<global::System.Boolean> _MMS_request;
        partial void OnMMS_requestChanging(Nullable<global::System.Boolean> value);
        partial void OnMMS_requestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MMS_resp_status
        {
            get
            {
                return _MMS_resp_status;
            }
            set
            {
                OnMMS_resp_statusChanging(value);
                ReportPropertyChanging("MMS_resp_status");
                _MMS_resp_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MMS_resp_status");
                OnMMS_resp_statusChanged();
            }
        }
        private Nullable<global::System.Int32> _MMS_resp_status;
        partial void OnMMS_resp_statusChanging(Nullable<global::System.Int32> value);
        partial void OnMMS_resp_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Delivery_Report
        {
            get
            {
                return _Delivery_Report;
            }
            set
            {
                OnDelivery_ReportChanging(value);
                ReportPropertyChanging("Delivery_Report");
                _Delivery_Report = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delivery_Report");
                OnDelivery_ReportChanged();
            }
        }
        private Nullable<global::System.Boolean> _Delivery_Report;
        partial void OnDelivery_ReportChanging(Nullable<global::System.Boolean> value);
        partial void OnDelivery_ReportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Query_Name
        {
            get
            {
                return _Query_Name;
            }
            set
            {
                OnQuery_NameChanging(value);
                ReportPropertyChanging("Query_Name");
                _Query_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Query_Name");
                OnQuery_NameChanged();
            }
        }
        private global::System.String _Query_Name;
        partial void OnQuery_NameChanging(global::System.String value);
        partial void OnQuery_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Query_Type
        {
            get
            {
                return _Query_Type;
            }
            set
            {
                OnQuery_TypeChanging(value);
                ReportPropertyChanging("Query_Type");
                _Query_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Query_Type");
                OnQuery_TypeChanged();
            }
        }
        private global::System.String _Query_Type;
        partial void OnQuery_TypeChanging(global::System.String value);
        partial void OnQuery_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DNS_TTL
        {
            get
            {
                return _DNS_TTL;
            }
            set
            {
                OnDNS_TTLChanging(value);
                ReportPropertyChanging("DNS_TTL");
                _DNS_TTL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNS_TTL");
                OnDNS_TTLChanged();
            }
        }
        private Nullable<global::System.Int32> _DNS_TTL;
        partial void OnDNS_TTLChanging(Nullable<global::System.Int32> value);
        partial void OnDNS_TTLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SP_Address
        {
            get
            {
                return _SP_Address;
            }
            set
            {
                OnSP_AddressChanging(value);
                ReportPropertyChanging("SP_Address");
                _SP_Address = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SP_Address");
                OnSP_AddressChanged();
            }
        }
        private Nullable<global::System.Int64> _SP_Address;
        partial void OnSP_AddressChanging(Nullable<global::System.Int64> value);
        partial void OnSP_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Identifier
        {
            get
            {
                return _Identifier;
            }
            set
            {
                OnIdentifierChanging(value);
                ReportPropertyChanging("Identifier");
                _Identifier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Identifier");
                OnIdentifierChanged();
            }
        }
        private Nullable<global::System.Int32> _Identifier;
        partial void OnIdentifierChanging(Nullable<global::System.Int32> value);
        partial void OnIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Is_UserAbnormal
        {
            get
            {
                return _Is_UserAbnormal;
            }
            set
            {
                OnIs_UserAbnormalChanging(value);
                ReportPropertyChanging("Is_UserAbnormal");
                _Is_UserAbnormal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Is_UserAbnormal");
                OnIs_UserAbnormalChanged();
            }
        }
        private Nullable<global::System.Int32> _Is_UserAbnormal;
        partial void OnIs_UserAbnormalChanging(Nullable<global::System.Int32> value);
        partial void OnIs_UserAbnormalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ErrorPacketLost
        {
            get
            {
                return _ErrorPacketLost;
            }
            set
            {
                OnErrorPacketLostChanging(value);
                ReportPropertyChanging("ErrorPacketLost");
                _ErrorPacketLost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketLost");
                OnErrorPacketLostChanged();
            }
        }
        private Nullable<global::System.Int32> _ErrorPacketLost;
        partial void OnErrorPacketLostChanging(Nullable<global::System.Int32> value);
        partial void OnErrorPacketLostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ErrorPacketWired
        {
            get
            {
                return _ErrorPacketWired;
            }
            set
            {
                OnErrorPacketWiredChanging(value);
                ReportPropertyChanging("ErrorPacketWired");
                _ErrorPacketWired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketWired");
                OnErrorPacketWiredChanged();
            }
        }
        private Nullable<global::System.Int32> _ErrorPacketWired;
        partial void OnErrorPacketWiredChanging(Nullable<global::System.Int32> value);
        partial void OnErrorPacketWiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ErrorPacketWireless
        {
            get
            {
                return _ErrorPacketWireless;
            }
            set
            {
                OnErrorPacketWirelessChanging(value);
                ReportPropertyChanging("ErrorPacketWireless");
                _ErrorPacketWireless = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorPacketWireless");
                OnErrorPacketWirelessChanged();
            }
        }
        private Nullable<global::System.Int32> _ErrorPacketWireless;
        partial void OnErrorPacketWirelessChanging(Nullable<global::System.Int32> value);
        partial void OnErrorPacketWirelessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ack
        {
            get
            {
                return _Ack;
            }
            set
            {
                OnAckChanging(value);
                ReportPropertyChanging("Ack");
                _Ack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ack");
                OnAckChanged();
            }
        }
        private Nullable<global::System.Int32> _Ack;
        partial void OnAckChanging(Nullable<global::System.Int32> value);
        partial void OnAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IpLenDlAck
        {
            get
            {
                return _IpLenDlAck;
            }
            set
            {
                OnIpLenDlAckChanging(value);
                ReportPropertyChanging("IpLenDlAck");
                _IpLenDlAck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IpLenDlAck");
                OnIpLenDlAckChanged();
            }
        }
        private Nullable<global::System.Int32> _IpLenDlAck;
        partial void OnIpLenDlAckChanging(Nullable<global::System.Int32> value);
        partial void OnIpLenDlAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IpLenUpAck
        {
            get
            {
                return _IpLenUpAck;
            }
            set
            {
                OnIpLenUpAckChanging(value);
                ReportPropertyChanging("IpLenUpAck");
                _IpLenUpAck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IpLenUpAck");
                OnIpLenUpAckChanged();
            }
        }
        private Nullable<global::System.Int32> _IpLenUpAck;
        partial void OnIpLenUpAckChanging(Nullable<global::System.Int32> value);
        partial void OnIpLenUpAckChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SynDirection
        {
            get
            {
                return _SynDirection;
            }
            set
            {
                OnSynDirectionChanging(value);
                ReportPropertyChanging("SynDirection");
                _SynDirection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SynDirection");
                OnSynDirectionChanged();
            }
        }
        private Nullable<global::System.Int32> _SynDirection;
        partial void OnSynDirectionChanging(Nullable<global::System.Int32> value);
        partial void OnSynDirectionChanged();

        #endregion
    
    }

    #endregion
    
}
