//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MutliInterfaceGnGi.ServerEntity.Gb
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class GuangZhou_GbEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“GuangZhou_GbEntities”部分中的连接字符串初始化新 GuangZhou_GbEntities 对象。
        /// </summary>
        public GuangZhou_GbEntities() : base("name=GuangZhou_GbEntities", "GuangZhou_GbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GuangZhou_GbEntities 对象。
        /// </summary>
        public GuangZhou_GbEntities(string connectionString) : base(connectionString, "GuangZhou_GbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GuangZhou_GbEntities 对象。
        /// </summary>
        public GuangZhou_GbEntities(EntityConnection connection) : base(connection, "GuangZhou_GbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Gb_FlowControly> Gb_FlowControly
        {
            get
            {
                if ((_Gb_FlowControly == null))
                {
                    _Gb_FlowControly = base.CreateObjectSet<Gb_FlowControly>("Gb_FlowControly");
                }
                return _Gb_FlowControly;
            }
        }
        private ObjectSet<Gb_FlowControly> _Gb_FlowControly;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Gb_FlowControly EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGb_FlowControly(Gb_FlowControly gb_FlowControly)
        {
            base.AddObject("Gb_FlowControly", gb_FlowControly);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GbModel", Name="Gb_FlowControly")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gb_FlowControly : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Gb_FlowControly 对象。
        /// </summary>
        /// <param name="fileNum">FileNum 属性的初始值。</param>
        /// <param name="packetNum">PacketNum 属性的初始值。</param>
        public static Gb_FlowControly CreateGb_FlowControly(global::System.Int32 fileNum, global::System.Int32 packetNum)
        {
            Gb_FlowControly gb_FlowControly = new Gb_FlowControly();
            gb_FlowControly.FileNum = fileNum;
            gb_FlowControly.PacketNum = packetNum;
            return gb_FlowControly;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileNum
        {
            get
            {
                return _FileNum;
            }
            set
            {
                if (_FileNum != value)
                {
                    OnFileNumChanging(value);
                    ReportPropertyChanging("FileNum");
                    _FileNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileNum");
                    OnFileNumChanged();
                }
            }
        }
        private global::System.Int32 _FileNum;
        partial void OnFileNumChanging(global::System.Int32 value);
        partial void OnFileNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PacketNum
        {
            get
            {
                return _PacketNum;
            }
            set
            {
                if (_PacketNum != value)
                {
                    OnPacketNumChanging(value);
                    ReportPropertyChanging("PacketNum");
                    _PacketNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PacketNum");
                    OnPacketNumChanged();
                }
            }
        }
        private global::System.Int32 _PacketNum;
        partial void OnPacketNumChanging(global::System.Int32 value);
        partial void OnPacketNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFileNum
        {
            get
            {
                return _BeginFileNum;
            }
            set
            {
                OnBeginFileNumChanging(value);
                ReportPropertyChanging("BeginFileNum");
                _BeginFileNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFileNum");
                OnBeginFileNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFileNum;
        partial void OnBeginFileNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFileNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFrameNum
        {
            get
            {
                return _BeginFrameNum;
            }
            set
            {
                OnBeginFrameNumChanging(value);
                ReportPropertyChanging("BeginFrameNum");
                _BeginFrameNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFrameNum");
                OnBeginFrameNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFrameNum;
        partial void OnBeginFrameNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFrameNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PacketTime
        {
            get
            {
                return _PacketTime;
            }
            set
            {
                OnPacketTimeChanging(value);
                ReportPropertyChanging("PacketTime");
                _PacketTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime");
                OnPacketTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PacketTime;
        partial void OnPacketTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPacketTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PacketTime_ms_
        {
            get
            {
                return _PacketTime_ms_;
            }
            set
            {
                OnPacketTime_ms_Changing(value);
                ReportPropertyChanging("PacketTime_ms_");
                _PacketTime_ms_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime_ms_");
                OnPacketTime_ms_Changed();
            }
        }
        private Nullable<global::System.Int32> _PacketTime_ms_;
        partial void OnPacketTime_ms_Changing(Nullable<global::System.Int32> value);
        partial void OnPacketTime_ms_Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DumpFor
        {
            get
            {
                return _DumpFor;
            }
            set
            {
                OnDumpForChanging(value);
                ReportPropertyChanging("DumpFor");
                _DumpFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DumpFor");
                OnDumpForChanged();
            }
        }
        private global::System.String _DumpFor;
        partial void OnDumpForChanging(global::System.String value);
        partial void OnDumpForChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flow_Control
        {
            get
            {
                return _Flow_Control;
            }
            set
            {
                OnFlow_ControlChanging(value);
                ReportPropertyChanging("Flow_Control");
                _Flow_Control = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flow_Control");
                OnFlow_ControlChanged();
            }
        }
        private Nullable<global::System.Int32> _Flow_Control;
        partial void OnFlow_ControlChanging(Nullable<global::System.Int32> value);
        partial void OnFlow_ControlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Flow_Control_time
        {
            get
            {
                return _Flow_Control_time;
            }
            set
            {
                OnFlow_Control_timeChanging(value);
                ReportPropertyChanging("Flow_Control_time");
                _Flow_Control_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Flow_Control_time");
                OnFlow_Control_timeChanged();
            }
        }
        private global::System.String _Flow_Control_time;
        partial void OnFlow_Control_timeChanging(global::System.String value);
        partial void OnFlow_Control_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Flow_Control_MsgType
        {
            get
            {
                return _Flow_Control_MsgType;
            }
            set
            {
                OnFlow_Control_MsgTypeChanging(value);
                ReportPropertyChanging("Flow_Control_MsgType");
                _Flow_Control_MsgType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Flow_Control_MsgType");
                OnFlow_Control_MsgTypeChanged();
            }
        }
        private global::System.String _Flow_Control_MsgType;
        partial void OnFlow_Control_MsgTypeChanging(global::System.String value);
        partial void OnFlow_Control_MsgTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_window_size
        {
            get
            {
                return _tcp_window_size;
            }
            set
            {
                Ontcp_window_sizeChanging(value);
                ReportPropertyChanging("tcp_window_size");
                _tcp_window_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_window_size");
                Ontcp_window_sizeChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_window_size;
        partial void Ontcp_window_sizeChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_window_sizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_srcport
        {
            get
            {
                return _tcp_srcport;
            }
            set
            {
                Ontcp_srcportChanging(value);
                ReportPropertyChanging("tcp_srcport");
                _tcp_srcport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_srcport");
                Ontcp_srcportChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_srcport;
        partial void Ontcp_srcportChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_srcportChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_seq
        {
            get
            {
                return _tcp_seq;
            }
            set
            {
                Ontcp_seqChanging(value);
                ReportPropertyChanging("tcp_seq");
                _tcp_seq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_seq");
                Ontcp_seqChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_seq;
        partial void Ontcp_seqChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_seqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_nxtseq
        {
            get
            {
                return _tcp_nxtseq;
            }
            set
            {
                Ontcp_nxtseqChanging(value);
                ReportPropertyChanging("tcp_nxtseq");
                _tcp_nxtseq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_nxtseq");
                Ontcp_nxtseqChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_nxtseq;
        partial void Ontcp_nxtseqChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_nxtseqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_need_segment
        {
            get
            {
                return _tcp_need_segment;
            }
            set
            {
                Ontcp_need_segmentChanging(value);
                ReportPropertyChanging("tcp_need_segment");
                _tcp_need_segment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_need_segment");
                Ontcp_need_segmentChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_need_segment;
        partial void Ontcp_need_segmentChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_need_segmentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_dstport
        {
            get
            {
                return _tcp_dstport;
            }
            set
            {
                Ontcp_dstportChanging(value);
                ReportPropertyChanging("tcp_dstport");
                _tcp_dstport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_dstport");
                Ontcp_dstportChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_dstport;
        partial void Ontcp_dstportChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_dstportChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_ack
        {
            get
            {
                return _tcp_ack;
            }
            set
            {
                Ontcp_ackChanging(value);
                ReportPropertyChanging("tcp_ack");
                _tcp_ack = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_ack");
                Ontcp_ackChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_ack;
        partial void Ontcp_ackChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_ackChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_ttl
        {
            get
            {
                return _ip2_ttl;
            }
            set
            {
                Onip2_ttlChanging(value);
                ReportPropertyChanging("ip2_ttl");
                _ip2_ttl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_ttl");
                Onip2_ttlChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_ttl;
        partial void Onip2_ttlChanging(Nullable<global::System.Int32> value);
        partial void Onip2_ttlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_src_host
        {
            get
            {
                return _ip2_src_host;
            }
            set
            {
                Onip2_src_hostChanging(value);
                ReportPropertyChanging("ip2_src_host");
                _ip2_src_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_src_host");
                Onip2_src_hostChanged();
            }
        }
        private global::System.String _ip2_src_host;
        partial void Onip2_src_hostChanging(global::System.String value);
        partial void Onip2_src_hostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_len
        {
            get
            {
                return _ip2_len;
            }
            set
            {
                Onip2_lenChanging(value);
                ReportPropertyChanging("ip2_len");
                _ip2_len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_len");
                Onip2_lenChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_len;
        partial void Onip2_lenChanging(Nullable<global::System.Int32> value);
        partial void Onip2_lenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_frag_offset
        {
            get
            {
                return _ip2_frag_offset;
            }
            set
            {
                Onip2_frag_offsetChanging(value);
                ReportPropertyChanging("ip2_frag_offset");
                _ip2_frag_offset = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_frag_offset");
                Onip2_frag_offsetChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_frag_offset;
        partial void Onip2_frag_offsetChanging(Nullable<global::System.Int32> value);
        partial void Onip2_frag_offsetChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_flags_rb
        {
            get
            {
                return _ip2_flags_rb;
            }
            set
            {
                Onip2_flags_rbChanging(value);
                ReportPropertyChanging("ip2_flags_rb");
                _ip2_flags_rb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_flags_rb");
                Onip2_flags_rbChanged();
            }
        }
        private global::System.String _ip2_flags_rb;
        partial void Onip2_flags_rbChanging(global::System.String value);
        partial void Onip2_flags_rbChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_flags_mf
        {
            get
            {
                return _ip2_flags_mf;
            }
            set
            {
                Onip2_flags_mfChanging(value);
                ReportPropertyChanging("ip2_flags_mf");
                _ip2_flags_mf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_flags_mf");
                Onip2_flags_mfChanged();
            }
        }
        private global::System.String _ip2_flags_mf;
        partial void Onip2_flags_mfChanging(global::System.String value);
        partial void Onip2_flags_mfChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_flags_df
        {
            get
            {
                return _ip2_flags_df;
            }
            set
            {
                Onip2_flags_dfChanging(value);
                ReportPropertyChanging("ip2_flags_df");
                _ip2_flags_df = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_flags_df");
                Onip2_flags_dfChanged();
            }
        }
        private global::System.String _ip2_flags_df;
        partial void Onip2_flags_dfChanging(global::System.String value);
        partial void Onip2_flags_dfChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_flags
        {
            get
            {
                return _ip2_flags;
            }
            set
            {
                Onip2_flagsChanging(value);
                ReportPropertyChanging("ip2_flags");
                _ip2_flags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_flags");
                Onip2_flagsChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_flags;
        partial void Onip2_flagsChanging(Nullable<global::System.Int32> value);
        partial void Onip2_flagsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_dst_host
        {
            get
            {
                return _ip2_dst_host;
            }
            set
            {
                Onip2_dst_hostChanging(value);
                ReportPropertyChanging("ip2_dst_host");
                _ip2_dst_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_dst_host");
                Onip2_dst_hostChanged();
            }
        }
        private global::System.String _ip2_dst_host;
        partial void Onip2_dst_hostChanging(global::System.String value);
        partial void Onip2_dst_hostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_ttl
        {
            get
            {
                return _ip_ttl;
            }
            set
            {
                Onip_ttlChanging(value);
                ReportPropertyChanging("ip_ttl");
                _ip_ttl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_ttl");
                Onip_ttlChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_ttl;
        partial void Onip_ttlChanging(Nullable<global::System.Int32> value);
        partial void Onip_ttlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_src_host
        {
            get
            {
                return _ip_src_host;
            }
            set
            {
                Onip_src_hostChanging(value);
                ReportPropertyChanging("ip_src_host");
                _ip_src_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_src_host");
                Onip_src_hostChanged();
            }
        }
        private global::System.String _ip_src_host;
        partial void Onip_src_hostChanging(global::System.String value);
        partial void Onip_src_hostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_len
        {
            get
            {
                return _ip_len;
            }
            set
            {
                Onip_lenChanging(value);
                ReportPropertyChanging("ip_len");
                _ip_len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_len");
                Onip_lenChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_len;
        partial void Onip_lenChanging(Nullable<global::System.Int32> value);
        partial void Onip_lenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_frag_offset
        {
            get
            {
                return _ip_frag_offset;
            }
            set
            {
                Onip_frag_offsetChanging(value);
                ReportPropertyChanging("ip_frag_offset");
                _ip_frag_offset = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_frag_offset");
                Onip_frag_offsetChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_frag_offset;
        partial void Onip_frag_offsetChanging(Nullable<global::System.Int32> value);
        partial void Onip_frag_offsetChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_flags_rb
        {
            get
            {
                return _ip_flags_rb;
            }
            set
            {
                Onip_flags_rbChanging(value);
                ReportPropertyChanging("ip_flags_rb");
                _ip_flags_rb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_flags_rb");
                Onip_flags_rbChanged();
            }
        }
        private global::System.String _ip_flags_rb;
        partial void Onip_flags_rbChanging(global::System.String value);
        partial void Onip_flags_rbChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_flags_mf
        {
            get
            {
                return _ip_flags_mf;
            }
            set
            {
                Onip_flags_mfChanging(value);
                ReportPropertyChanging("ip_flags_mf");
                _ip_flags_mf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_flags_mf");
                Onip_flags_mfChanged();
            }
        }
        private global::System.String _ip_flags_mf;
        partial void Onip_flags_mfChanging(global::System.String value);
        partial void Onip_flags_mfChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_flags_df
        {
            get
            {
                return _ip_flags_df;
            }
            set
            {
                Onip_flags_dfChanging(value);
                ReportPropertyChanging("ip_flags_df");
                _ip_flags_df = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_flags_df");
                Onip_flags_dfChanged();
            }
        }
        private global::System.String _ip_flags_df;
        partial void Onip_flags_dfChanging(global::System.String value);
        partial void Onip_flags_dfChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_flags
        {
            get
            {
                return _ip_flags;
            }
            set
            {
                Onip_flagsChanging(value);
                ReportPropertyChanging("ip_flags");
                _ip_flags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_flags");
                Onip_flagsChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_flags;
        partial void Onip_flagsChanging(Nullable<global::System.Int32> value);
        partial void Onip_flagsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_dst_host
        {
            get
            {
                return _ip_dst_host;
            }
            set
            {
                Onip_dst_hostChanging(value);
                ReportPropertyChanging("ip_dst_host");
                _ip_dst_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_dst_host");
                Onip_dst_hostChanged();
            }
        }
        private global::System.String _ip_dst_host;
        partial void Onip_dst_hostChanging(global::System.String value);
        partial void Onip_dst_hostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gtp_seq_number
        {
            get
            {
                return _gtp_seq_number;
            }
            set
            {
                Ongtp_seq_numberChanging(value);
                ReportPropertyChanging("gtp_seq_number");
                _gtp_seq_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gtp_seq_number");
                Ongtp_seq_numberChanged();
            }
        }
        private Nullable<global::System.Int32> _gtp_seq_number;
        partial void Ongtp_seq_numberChanging(Nullable<global::System.Int32> value);
        partial void Ongtp_seq_numberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gtp_length
        {
            get
            {
                return _gtp_length;
            }
            set
            {
                Ongtp_lengthChanging(value);
                ReportPropertyChanging("gtp_length");
                _gtp_length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gtp_length");
                Ongtp_lengthChanged();
            }
        }
        private Nullable<global::System.Int32> _gtp_length;
        partial void Ongtp_lengthChanging(Nullable<global::System.Int32> value);
        partial void Ongtp_lengthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tcp_flags_cwr
        {
            get
            {
                return _tcp_flags_cwr;
            }
            set
            {
                Ontcp_flags_cwrChanging(value);
                ReportPropertyChanging("tcp_flags_cwr");
                _tcp_flags_cwr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tcp_flags_cwr");
                Ontcp_flags_cwrChanged();
            }
        }
        private global::System.String _tcp_flags_cwr;
        partial void Ontcp_flags_cwrChanging(global::System.String value);
        partial void Ontcp_flags_cwrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_options_mss_val
        {
            get
            {
                return _tcp_options_mss_val;
            }
            set
            {
                Ontcp_options_mss_valChanging(value);
                ReportPropertyChanging("tcp_options_mss_val");
                _tcp_options_mss_val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_options_mss_val");
                Ontcp_options_mss_valChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_options_mss_val;
        partial void Ontcp_options_mss_valChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_options_mss_valChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_options_wscale_val
        {
            get
            {
                return _tcp_options_wscale_val;
            }
            set
            {
                Ontcp_options_wscale_valChanging(value);
                ReportPropertyChanging("tcp_options_wscale_val");
                _tcp_options_wscale_val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_options_wscale_val");
                Ontcp_options_wscale_valChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_options_wscale_val;
        partial void Ontcp_options_wscale_valChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_options_wscale_valChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_lac
        {
            get
            {
                return _bssgp_lac;
            }
            set
            {
                Onbssgp_lacChanging(value);
                ReportPropertyChanging("bssgp_lac");
                _bssgp_lac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_lac");
                Onbssgp_lacChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_lac;
        partial void Onbssgp_lacChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_lacChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_ci
        {
            get
            {
                return _bssgp_ci;
            }
            set
            {
                Onbssgp_ciChanging(value);
                ReportPropertyChanging("bssgp_ci");
                _bssgp_ci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_ci");
                Onbssgp_ciChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_ci;
        partial void Onbssgp_ciChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_ciChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nsip_bvci
        {
            get
            {
                return _nsip_bvci;
            }
            set
            {
                Onnsip_bvciChanging(value);
                ReportPropertyChanging("nsip_bvci");
                _nsip_bvci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nsip_bvci");
                Onnsip_bvciChanged();
            }
        }
        private Nullable<global::System.Int32> _nsip_bvci;
        partial void Onnsip_bvciChanging(Nullable<global::System.Int32> value);
        partial void Onnsip_bvciChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bssgp_drx_cycle
        {
            get
            {
                return _bssgp_drx_cycle;
            }
            set
            {
                Onbssgp_drx_cycleChanging(value);
                ReportPropertyChanging("bssgp_drx_cycle");
                _bssgp_drx_cycle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bssgp_drx_cycle");
                Onbssgp_drx_cycleChanged();
            }
        }
        private global::System.String _bssgp_drx_cycle;
        partial void Onbssgp_drx_cycleChanging(global::System.String value);
        partial void Onbssgp_drx_cycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bssgp_direction
        {
            get
            {
                return _bssgp_direction;
            }
            set
            {
                Onbssgp_directionChanging(value);
                ReportPropertyChanging("bssgp_direction");
                _bssgp_direction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bssgp_direction");
                Onbssgp_directionChanged();
            }
        }
        private global::System.String _bssgp_direction;
        partial void Onbssgp_directionChanging(global::System.String value);
        partial void Onbssgp_directionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bssgp_drx_timer
        {
            get
            {
                return _bssgp_drx_timer;
            }
            set
            {
                Onbssgp_drx_timerChanging(value);
                ReportPropertyChanging("bssgp_drx_timer");
                _bssgp_drx_timer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bssgp_drx_timer");
                Onbssgp_drx_timerChanged();
            }
        }
        private global::System.String _bssgp_drx_timer;
        partial void Onbssgp_drx_timerChanging(global::System.String value);
        partial void Onbssgp_drx_timerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sndcp_segment
        {
            get
            {
                return _sndcp_segment;
            }
            set
            {
                Onsndcp_segmentChanging(value);
                ReportPropertyChanging("sndcp_segment");
                _sndcp_segment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sndcp_segment");
                Onsndcp_segmentChanged();
            }
        }
        private Nullable<global::System.Int32> _sndcp_segment;
        partial void Onsndcp_segmentChanging(Nullable<global::System.Int32> value);
        partial void Onsndcp_segmentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sndcp_m
        {
            get
            {
                return _sndcp_m;
            }
            set
            {
                Onsndcp_mChanging(value);
                ReportPropertyChanging("sndcp_m");
                _sndcp_m = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sndcp_m");
                Onsndcp_mChanged();
            }
        }
        private global::System.String _sndcp_m;
        partial void Onsndcp_mChanging(global::System.String value);
        partial void Onsndcp_mChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> udp_length
        {
            get
            {
                return _udp_length;
            }
            set
            {
                Onudp_lengthChanging(value);
                ReportPropertyChanging("udp_length");
                _udp_length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("udp_length");
                Onudp_lengthChanged();
            }
        }
        private Nullable<global::System.Int32> _udp_length;
        partial void Onudp_lengthChanging(Nullable<global::System.Int32> value);
        partial void Onudp_lengthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gsm_a_imeisv
        {
            get
            {
                return _gsm_a_imeisv;
            }
            set
            {
                Ongsm_a_imeisvChanging(value);
                ReportPropertyChanging("gsm_a_imeisv");
                _gsm_a_imeisv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gsm_a_imeisv");
                Ongsm_a_imeisvChanged();
            }
        }
        private global::System.String _gsm_a_imeisv;
        partial void Ongsm_a_imeisvChanging(global::System.String value);
        partial void Ongsm_a_imeisvChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_ms_bucket_size
        {
            get
            {
                return _bssgp_ms_bucket_size;
            }
            set
            {
                Onbssgp_ms_bucket_sizeChanging(value);
                ReportPropertyChanging("bssgp_ms_bucket_size");
                _bssgp_ms_bucket_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_ms_bucket_size");
                Onbssgp_ms_bucket_sizeChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_ms_bucket_size;
        partial void Onbssgp_ms_bucket_sizeChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_ms_bucket_sizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_bucket_leak_rate
        {
            get
            {
                return _bssgp_bucket_leak_rate;
            }
            set
            {
                Onbssgp_bucket_leak_rateChanging(value);
                ReportPropertyChanging("bssgp_bucket_leak_rate");
                _bssgp_bucket_leak_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_bucket_leak_rate");
                Onbssgp_bucket_leak_rateChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_bucket_leak_rate;
        partial void Onbssgp_bucket_leak_rateChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_bucket_leak_rateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_bvc_bucket_size
        {
            get
            {
                return _bssgp_bvc_bucket_size;
            }
            set
            {
                Onbssgp_bvc_bucket_sizeChanging(value);
                ReportPropertyChanging("bssgp_bvc_bucket_size");
                _bssgp_bvc_bucket_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_bvc_bucket_size");
                Onbssgp_bvc_bucket_sizeChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_bvc_bucket_size;
        partial void Onbssgp_bvc_bucket_sizeChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_bvc_bucket_sizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_bmax_default_ms
        {
            get
            {
                return _bssgp_bmax_default_ms;
            }
            set
            {
                Onbssgp_bmax_default_msChanging(value);
                ReportPropertyChanging("bssgp_bmax_default_ms");
                _bssgp_bmax_default_ms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_bmax_default_ms");
                Onbssgp_bmax_default_msChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_bmax_default_ms;
        partial void Onbssgp_bmax_default_msChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_bmax_default_msChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_R_default_ms
        {
            get
            {
                return _bssgp_R_default_ms;
            }
            set
            {
                Onbssgp_R_default_msChanging(value);
                ReportPropertyChanging("bssgp_R_default_ms");
                _bssgp_R_default_ms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_R_default_ms");
                Onbssgp_R_default_msChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_R_default_ms;
        partial void Onbssgp_R_default_msChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_R_default_msChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bssgp_bucket_full_ratio
        {
            get
            {
                return _bssgp_bucket_full_ratio;
            }
            set
            {
                Onbssgp_bucket_full_ratioChanging(value);
                ReportPropertyChanging("bssgp_bucket_full_ratio");
                _bssgp_bucket_full_ratio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bssgp_bucket_full_ratio");
                Onbssgp_bucket_full_ratioChanged();
            }
        }
        private Nullable<global::System.Int32> _bssgp_bucket_full_ratio;
        partial void Onbssgp_bucket_full_ratioChanging(Nullable<global::System.Int32> value);
        partial void Onbssgp_bucket_full_ratioChanged();

        #endregion
    
    }

    #endregion
    
}
