//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EntityClass.ServerEntity.Gn
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GuangZhou_GnEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GuangZhou_GnEntities2 object using the connection string found in the 'GuangZhou_GnEntities2' section of the application configuration file.
        /// </summary>
        public GuangZhou_GnEntities2() : base("name=GuangZhou_GnEntities2", "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities2 object.
        /// </summary>
        public GuangZhou_GnEntities2(string connectionString) : base(connectionString, "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GuangZhou_GnEntities2 object.
        /// </summary>
        public GuangZhou_GnEntities2(EntityConnection connection) : base(connection, "GuangZhou_GnEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GnGiGw_Http_Any_Multi> GnGiGw_Http_Any_Multi
        {
            get
            {
                if ((_GnGiGw_Http_Any_Multi == null))
                {
                    _GnGiGw_Http_Any_Multi = base.CreateObjectSet<GnGiGw_Http_Any_Multi>("GnGiGw_Http_Any_Multi");
                }
                return _GnGiGw_Http_Any_Multi;
            }
        }
        private ObjectSet<GnGiGw_Http_Any_Multi> _GnGiGw_Http_Any_Multi;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GnGiGw_Http_Any_Multi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGnGiGw_Http_Any_Multi(GnGiGw_Http_Any_Multi gnGiGw_Http_Any_Multi)
        {
            base.AddObject("GnGiGw_Http_Any_Multi", gnGiGw_Http_Any_Multi);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GuangZhou_GnModel5", Name="GnGiGw_Http_Any_Multi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GnGiGw_Http_Any_Multi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GnGiGw_Http_Any_Multi object.
        /// </summary>
        /// <param name="fileNum">Initial value of the FileNum property.</param>
        /// <param name="packetNum">Initial value of the PacketNum property.</param>
        public static GnGiGw_Http_Any_Multi CreateGnGiGw_Http_Any_Multi(global::System.Int32 fileNum, global::System.Int32 packetNum)
        {
            GnGiGw_Http_Any_Multi gnGiGw_Http_Any_Multi = new GnGiGw_Http_Any_Multi();
            gnGiGw_Http_Any_Multi.FileNum = fileNum;
            gnGiGw_Http_Any_Multi.PacketNum = packetNum;
            return gnGiGw_Http_Any_Multi;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileNum
        {
            get
            {
                return _FileNum;
            }
            set
            {
                if (_FileNum != value)
                {
                    OnFileNumChanging(value);
                    ReportPropertyChanging("FileNum");
                    _FileNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileNum");
                    OnFileNumChanged();
                }
            }
        }
        private global::System.Int32 _FileNum;
        partial void OnFileNumChanging(global::System.Int32 value);
        partial void OnFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PacketNum
        {
            get
            {
                return _PacketNum;
            }
            set
            {
                if (_PacketNum != value)
                {
                    OnPacketNumChanging(value);
                    ReportPropertyChanging("PacketNum");
                    _PacketNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PacketNum");
                    OnPacketNumChanged();
                }
            }
        }
        private global::System.Int32 _PacketNum;
        partial void OnPacketNumChanging(global::System.Int32 value);
        partial void OnPacketNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFileNum
        {
            get
            {
                return _BeginFileNum;
            }
            set
            {
                OnBeginFileNumChanging(value);
                ReportPropertyChanging("BeginFileNum");
                _BeginFileNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFileNum");
                OnBeginFileNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFileNum;
        partial void OnBeginFileNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFileNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeginFrameNum
        {
            get
            {
                return _BeginFrameNum;
            }
            set
            {
                OnBeginFrameNumChanging(value);
                ReportPropertyChanging("BeginFrameNum");
                _BeginFrameNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginFrameNum");
                OnBeginFrameNumChanged();
            }
        }
        private Nullable<global::System.Int32> _BeginFrameNum;
        partial void OnBeginFrameNumChanging(Nullable<global::System.Int32> value);
        partial void OnBeginFrameNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PacketTime
        {
            get
            {
                return _PacketTime;
            }
            set
            {
                OnPacketTimeChanging(value);
                ReportPropertyChanging("PacketTime");
                _PacketTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime");
                OnPacketTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PacketTime;
        partial void OnPacketTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPacketTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PacketTime_ms_
        {
            get
            {
                return _PacketTime_ms_;
            }
            set
            {
                OnPacketTime_ms_Changing(value);
                ReportPropertyChanging("PacketTime_ms_");
                _PacketTime_ms_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketTime_ms_");
                OnPacketTime_ms_Changed();
            }
        }
        private Nullable<global::System.Int32> _PacketTime_ms_;
        partial void OnPacketTime_ms_Changing(Nullable<global::System.Int32> value);
        partial void OnPacketTime_ms_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DumpFor
        {
            get
            {
                return _DumpFor;
            }
            set
            {
                OnDumpForChanging(value);
                ReportPropertyChanging("DumpFor");
                _DumpFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DumpFor");
                OnDumpForChanged();
            }
        }
        private global::System.String _DumpFor;
        partial void OnDumpForChanging(global::System.String value);
        partial void OnDumpForChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Http_Any
        {
            get
            {
                return _Http_Any;
            }
            set
            {
                OnHttp_AnyChanging(value);
                ReportPropertyChanging("Http_Any");
                _Http_Any = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Http_Any");
                OnHttp_AnyChanged();
            }
        }
        private Nullable<global::System.Int32> _Http_Any;
        partial void OnHttp_AnyChanging(Nullable<global::System.Int32> value);
        partial void OnHttp_AnyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Http_Any_time
        {
            get
            {
                return _Http_Any_time;
            }
            set
            {
                OnHttp_Any_timeChanging(value);
                ReportPropertyChanging("Http_Any_time");
                _Http_Any_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Http_Any_time");
                OnHttp_Any_timeChanged();
            }
        }
        private global::System.String _Http_Any_time;
        partial void OnHttp_Any_timeChanging(global::System.String value);
        partial void OnHttp_Any_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Http_Any_MsgType
        {
            get
            {
                return _Http_Any_MsgType;
            }
            set
            {
                OnHttp_Any_MsgTypeChanging(value);
                ReportPropertyChanging("Http_Any_MsgType");
                _Http_Any_MsgType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Http_Any_MsgType");
                OnHttp_Any_MsgTypeChanged();
            }
        }
        private global::System.String _Http_Any_MsgType;
        partial void OnHttp_Any_MsgTypeChanging(global::System.String value);
        partial void OnHttp_Any_MsgTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Http_Any_RepeatCounter
        {
            get
            {
                return _Http_Any_RepeatCounter;
            }
            set
            {
                OnHttp_Any_RepeatCounterChanging(value);
                ReportPropertyChanging("Http_Any_RepeatCounter");
                _Http_Any_RepeatCounter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Http_Any_RepeatCounter");
                OnHttp_Any_RepeatCounterChanged();
            }
        }
        private Nullable<global::System.Int32> _Http_Any_RepeatCounter;
        partial void OnHttp_Any_RepeatCounterChanging(Nullable<global::System.Int32> value);
        partial void OnHttp_Any_RepeatCounterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_src_host
        {
            get
            {
                return _ip_src_host;
            }
            set
            {
                Onip_src_hostChanging(value);
                ReportPropertyChanging("ip_src_host");
                _ip_src_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_src_host");
                Onip_src_hostChanged();
            }
        }
        private global::System.String _ip_src_host;
        partial void Onip_src_hostChanging(global::System.String value);
        partial void Onip_src_hostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_dst_host
        {
            get
            {
                return _ip_dst_host;
            }
            set
            {
                Onip_dst_hostChanging(value);
                ReportPropertyChanging("ip_dst_host");
                _ip_dst_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_dst_host");
                Onip_dst_hostChanged();
            }
        }
        private global::System.String _ip_dst_host;
        partial void Onip_dst_hostChanging(global::System.String value);
        partial void Onip_dst_hostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> udp_srcport
        {
            get
            {
                return _udp_srcport;
            }
            set
            {
                Onudp_srcportChanging(value);
                ReportPropertyChanging("udp_srcport");
                _udp_srcport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("udp_srcport");
                Onudp_srcportChanged();
            }
        }
        private Nullable<global::System.Int32> _udp_srcport;
        partial void Onudp_srcportChanging(Nullable<global::System.Int32> value);
        partial void Onudp_srcportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> udp_dstport
        {
            get
            {
                return _udp_dstport;
            }
            set
            {
                Onudp_dstportChanging(value);
                ReportPropertyChanging("udp_dstport");
                _udp_dstport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("udp_dstport");
                Onudp_dstportChanged();
            }
        }
        private Nullable<global::System.Int32> _udp_dstport;
        partial void Onudp_dstportChanging(Nullable<global::System.Int32> value);
        partial void Onudp_dstportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_src_host
        {
            get
            {
                return _ip2_src_host;
            }
            set
            {
                Onip2_src_hostChanging(value);
                ReportPropertyChanging("ip2_src_host");
                _ip2_src_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_src_host");
                Onip2_src_hostChanged();
            }
        }
        private global::System.String _ip2_src_host;
        partial void Onip2_src_hostChanging(global::System.String value);
        partial void Onip2_src_hostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_dst_host
        {
            get
            {
                return _ip2_dst_host;
            }
            set
            {
                Onip2_dst_hostChanging(value);
                ReportPropertyChanging("ip2_dst_host");
                _ip2_dst_host = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_dst_host");
                Onip2_dst_hostChanged();
            }
        }
        private global::System.String _ip2_dst_host;
        partial void Onip2_dst_hostChanging(global::System.String value);
        partial void Onip2_dst_hostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String http_request_uri
        {
            get
            {
                return _http_request_uri;
            }
            set
            {
                Onhttp_request_uriChanging(value);
                ReportPropertyChanging("http_request_uri");
                _http_request_uri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("http_request_uri");
                Onhttp_request_uriChanged();
            }
        }
        private global::System.String _http_request_uri;
        partial void Onhttp_request_uriChanging(global::System.String value);
        partial void Onhttp_request_uriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String http_user_agent
        {
            get
            {
                return _http_user_agent;
            }
            set
            {
                Onhttp_user_agentChanging(value);
                ReportPropertyChanging("http_user_agent");
                _http_user_agent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("http_user_agent");
                Onhttp_user_agentChanged();
            }
        }
        private global::System.String _http_user_agent;
        partial void Onhttp_user_agentChanging(global::System.String value);
        partial void Onhttp_user_agentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_proto
        {
            get
            {
                return _ip_proto;
            }
            set
            {
                Onip_protoChanging(value);
                ReportPropertyChanging("ip_proto");
                _ip_proto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_proto");
                Onip_protoChanged();
            }
        }
        private global::System.String _ip_proto;
        partial void Onip_protoChanging(global::System.String value);
        partial void Onip_protoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_proto
        {
            get
            {
                return _ip2_proto;
            }
            set
            {
                Onip2_protoChanging(value);
                ReportPropertyChanging("ip2_proto");
                _ip2_proto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_proto");
                Onip2_protoChanged();
            }
        }
        private global::System.String _ip2_proto;
        partial void Onip2_protoChanging(global::System.String value);
        partial void Onip2_protoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_srcport
        {
            get
            {
                return _tcp_srcport;
            }
            set
            {
                Ontcp_srcportChanging(value);
                ReportPropertyChanging("tcp_srcport");
                _tcp_srcport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_srcport");
                Ontcp_srcportChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_srcport;
        partial void Ontcp_srcportChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_srcportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tcp_dstport
        {
            get
            {
                return _tcp_dstport;
            }
            set
            {
                Ontcp_dstportChanging(value);
                ReportPropertyChanging("tcp_dstport");
                _tcp_dstport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tcp_dstport");
                Ontcp_dstportChanged();
            }
        }
        private Nullable<global::System.Int32> _tcp_dstport;
        partial void Ontcp_dstportChanging(Nullable<global::System.Int32> value);
        partial void Ontcp_dstportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tcp_seq
        {
            get
            {
                return _tcp_seq;
            }
            set
            {
                Ontcp_seqChanging(value);
                ReportPropertyChanging("tcp_seq");
                _tcp_seq = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tcp_seq");
                Ontcp_seqChanged();
            }
        }
        private global::System.String _tcp_seq;
        partial void Ontcp_seqChanging(global::System.String value);
        partial void Ontcp_seqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tcp_nxtseq
        {
            get
            {
                return _tcp_nxtseq;
            }
            set
            {
                Ontcp_nxtseqChanging(value);
                ReportPropertyChanging("tcp_nxtseq");
                _tcp_nxtseq = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tcp_nxtseq");
                Ontcp_nxtseqChanged();
            }
        }
        private global::System.String _tcp_nxtseq;
        partial void Ontcp_nxtseqChanging(global::System.String value);
        partial void Ontcp_nxtseqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tcp_need_segment
        {
            get
            {
                return _tcp_need_segment;
            }
            set
            {
                Ontcp_need_segmentChanging(value);
                ReportPropertyChanging("tcp_need_segment");
                _tcp_need_segment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tcp_need_segment");
                Ontcp_need_segmentChanged();
            }
        }
        private global::System.String _tcp_need_segment;
        partial void Ontcp_need_segmentChanging(global::System.String value);
        partial void Ontcp_need_segmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tcp_ack
        {
            get
            {
                return _tcp_ack;
            }
            set
            {
                Ontcp_ackChanging(value);
                ReportPropertyChanging("tcp_ack");
                _tcp_ack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tcp_ack");
                Ontcp_ackChanged();
            }
        }
        private global::System.String _tcp_ack;
        partial void Ontcp_ackChanging(global::System.String value);
        partial void Ontcp_ackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_ttl
        {
            get
            {
                return _ip_ttl;
            }
            set
            {
                Onip_ttlChanging(value);
                ReportPropertyChanging("ip_ttl");
                _ip_ttl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_ttl");
                Onip_ttlChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_ttl;
        partial void Onip_ttlChanging(Nullable<global::System.Int32> value);
        partial void Onip_ttlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_ttl
        {
            get
            {
                return _ip2_ttl;
            }
            set
            {
                Onip2_ttlChanging(value);
                ReportPropertyChanging("ip2_ttl");
                _ip2_ttl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_ttl");
                Onip2_ttlChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_ttl;
        partial void Onip2_ttlChanging(Nullable<global::System.Int32> value);
        partial void Onip2_ttlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_len
        {
            get
            {
                return _ip_len;
            }
            set
            {
                Onip_lenChanging(value);
                ReportPropertyChanging("ip_len");
                _ip_len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_len");
                Onip_lenChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_len;
        partial void Onip_lenChanging(Nullable<global::System.Int32> value);
        partial void Onip_lenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_len
        {
            get
            {
                return _ip2_len;
            }
            set
            {
                Onip2_lenChanging(value);
                ReportPropertyChanging("ip2_len");
                _ip2_len = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_len");
                Onip2_lenChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_len;
        partial void Onip2_lenChanging(Nullable<global::System.Int32> value);
        partial void Onip2_lenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip_id
        {
            get
            {
                return _ip_id;
            }
            set
            {
                Onip_idChanging(value);
                ReportPropertyChanging("ip_id");
                _ip_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip_id");
                Onip_idChanged();
            }
        }
        private Nullable<global::System.Int32> _ip_id;
        partial void Onip_idChanging(Nullable<global::System.Int32> value);
        partial void Onip_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ip2_id
        {
            get
            {
                return _ip2_id;
            }
            set
            {
                Onip2_idChanging(value);
                ReportPropertyChanging("ip2_id");
                _ip2_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ip2_id");
                Onip2_idChanged();
            }
        }
        private Nullable<global::System.Int32> _ip2_id;
        partial void Onip2_idChanging(Nullable<global::System.Int32> value);
        partial void Onip2_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_flags_mf
        {
            get
            {
                return _ip_flags_mf;
            }
            set
            {
                Onip_flags_mfChanging(value);
                ReportPropertyChanging("ip_flags_mf");
                _ip_flags_mf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_flags_mf");
                Onip_flags_mfChanged();
            }
        }
        private global::System.String _ip_flags_mf;
        partial void Onip_flags_mfChanging(global::System.String value);
        partial void Onip_flags_mfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip2_flags_mf
        {
            get
            {
                return _ip2_flags_mf;
            }
            set
            {
                Onip2_flags_mfChanging(value);
                ReportPropertyChanging("ip2_flags_mf");
                _ip2_flags_mf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip2_flags_mf");
                Onip2_flags_mfChanged();
            }
        }
        private global::System.String _ip2_flags_mf;
        partial void Onip2_flags_mfChanging(global::System.String value);
        partial void Onip2_flags_mfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gtp_flags_payload
        {
            get
            {
                return _gtp_flags_payload;
            }
            set
            {
                Ongtp_flags_payloadChanging(value);
                ReportPropertyChanging("gtp_flags_payload");
                _gtp_flags_payload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gtp_flags_payload");
                Ongtp_flags_payloadChanged();
            }
        }
        private global::System.String _gtp_flags_payload;
        partial void Ongtp_flags_payloadChanging(global::System.String value);
        partial void Ongtp_flags_payloadChanged();

        #endregion
    
    }

    #endregion
    
}
